### PR TITLE
Fix a bug where size+offset overflows

### LINKED ISSUE #583: just copying from the input repo generates io errors in a pipeline
output of get logs, like this for pretty much every file.
```
2016-06-23T20:00:08Z ERROR fuse.FileRead {"file":{"file":{"commit":{"repo":{"name":"prospector_input"},"id":"723e2340a6c94630a7ecc9051fba71da"},"path":"194/digitizer/BIH310090052_T_BI348.bson.gz"},"shard":{"fileModulus":"1"}},"error":"read more than we need; this is likely a bug"}
0 | cp: error reading '/pfs/prospector_input/194/digitizer/BIH310090052_T_BI348.bson.gz': Input/output error
0 | cp: failed to extend '/inputs/prospector_input/194/digitizer/BIH310090052_T_BI348.bson.gz': Input/output error
```

### PR DESCRIPTION
**Pull request by derekchiang**
Should fix #583.

### CODE REVIEW

File: src/server/pfs/drive/driver.go [hunk 1]
```diff
@@ -1283,7 +1283,8 @@ type fileReader struct {
 	index       int
 	reader      io.Reader
 	offset      int64
-	size        int64
+	size        int64 // how much data to read
+	size_read   int64 // how much data has been read
```
Comment (jdoliner) [inline src/server/pfs/drive/driver.go]: Whoa whoa whoa, no snake_case in go.

**Comment by sjezewski** [comment]
LGMT

Ideally we also have a test for the 'real world' use case hitting S3. But since we haven't been able to reproduce so far, and we want to validate if this fix works, lets make a separate issue for the S3 testing. (We may already have one)

image
