### PR TITLE
Fix a bug where putting a single object from an object store doesn't work

### LINKED ISSUE #1901: Get 'storage: object doesn't exist' when trying to load from GCS without -r flag
Hello!

I've been trying to load some data from GCS, and I'm getting a 'storage: object doesn't exist' error whenever I try to load without a -r flag.

I first tried loading the individual file intervals.csv into the repository at the path /tesla but got the aforementioned error
```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -f gs://tesla-data/metadata/intervals.csv && \
pachctl finish-commit somatic_variant_aligner_input master
```

Next I tried copying that file to it's own folder and loading the whole folder, but I got the same error.
```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -f gs://tesla-data/metadata/intervals && \
pachctl finish-commit somatic_variant_aligner_input master
```

Finally, I tried loading the whole folder with the -r flag, and the commit was successful.
```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -r -f gs://tesla-data/metadata/intervals && \
pachctl finish-commit somatic_variant_aligner_input master
```

I'm on version 1.4.7. Let me know if I can provide anything else or if I'm doing anything wrong.

Thanks!

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #1901

### CODE REVIEW

File: src/server/pfs/server/api_server.go [hunk 1]
```diff
@@ -451,7 +451,8 @@ func (a *apiServer) putFileObj(ctx context.Context, objClient obj.Client, reques
 		})
 		return eg.Wait()
 	}
-	return put(request.File.Path, url.Path)
+	// Joining Host and Path to retrieve the full path after "scheme://"
+	return put(request.File.Path, path.Join(url.Host, url.Path))
```
Comment (jdoliner) [inline src/server/pfs/server/api_server.go]: Is this correct? It's been a while since I touched this code buy I seem to remember that the bucket gets passed directly to the `objClient` so I think by `Join`ing `url.Host` we're adding the bucket name to the front of the object we're requesting which means we won't find the object.

Comment (derekchiang) [inline src/server/pfs/server/api_server.go]: Yeah I tested it.  See the documentation here: https://golang.org/pkg/net/url/#URL
