### PR TITLE
Prevent finishing commits with provenance by default

### LINKED ISSUE #6374: Job stuck in running if the meta commit is finished externally
In `2.0.0-alpha23`, if a user were to finish the meta commit while a job is running, the worker does not handle it correctly and the job is stuck in the `RUNNING` state.  Here are the master logs for the job:

```
updating job info, state: JOB_STARTING
started waiting for job inputs
updating job info, state: JOB_RUNNING
finished waiting for job inputs
started processing job running
started computing skipped and deleted datums
finished computing skipped and deleted datums
updating job info, state: JOB_RUNNING
started running and collecting datum set subtasks
errored running and collecting datum set subtasks: commit 09f06683ed28422db30d4c5debe5e64f in repo regression.meta has already finished
errored processing job running: commit 09f06683ed28422db30d4c5debe5e64f in repo regression.meta has already finished
processJob error: commit 09f06683ed28422db30d4c5debe5e64f in repo regression.meta has already finished, retrying in 552.330144ms
error stack:
github.com/pachyderm/pachyderm/v2/src/internal/grpcutil.ScrubGRPC
        /Users/brendon/src/github.com/pachyderm/pachyderm/src/internal/grpcutil/error.go:16
github.com/pachyderm/pachyderm/v2/src/server/worker/pipeline/transform.(*registry).processJobRunning.func2.2.1.1
        /Users/brendon/src/github.com/pachyderm/pachyderm/src/server/worker/pipeline/transform/registry.go:576
github.com/pachyderm/pachyderm/v2/src/internal/work.(*Master).RunSubtasksChan.func1.1.1
        /Users/brendon/src/github.com/pachyderm/pachyderm/src/internal/work/work.go:179
github.com/pachyderm/pachyderm/v2/src/internal/work.(*taskEntry).runSubtaskBlock.func1
        /Users/brendon/src/github.com/pachyderm/pachyderm/src/internal/work/task_queue.go:43
github.com/pachyderm/pachyderm/v2/src/internal/work.newTaskQueue.func1
        /Users/brendon/src/github.com/pachyderm/pachyderm/src/internal/work/task_queue.go:84
runtime.goexit
        /usr/local/Cellar/go/1.16.4/libexec/src/runtime/asm_amd64.s:1371
updating job info, state: JOB_RUNNING
master done running processJobs
fatal job error: context canceled
```

### PR DESCRIPTION
**Pull request by PFedak**
Fix #6374  (kind of), makes it clear that it's not an operation that should be done. Seems like we could also consider automatically finishing meta and output commits together in the driver. Maybe we should set `Error` in this case

### CODE REVIEW

**Comment by PFedak** [comment]
Fix #6374  (kind of), makes it clear that it's not an operation that should be done. Seems like we could also consider automatically finishing meta and output commits together in the driver. Maybe we should set `Error` in this case

File: src/server/pfs/cmds/cmds.go [hunk 1]
```diff
@@ -355,6 +356,7 @@ $ {{alias}} test -p XXX`,
 	}
 	finishCommit.Flags().StringVarP(&description, "message", "m", "", "A description of this commit's contents (overwrites any existing commit description)")
 	finishCommit.Flags().StringVar(&description, "description", "", "A description of this commit's contents (synonym for --message)")
+	finishCommit.Flags().BoolVarP(&force, "force", "f", false, "finish the commit even if it has provenance, which could break jobs; use with care")
```
Comment (Tryneus) [inline src/server/pfs/cmds/cmds.go:359]: maybe instead of `use with care` - `prefer using 'stop job'`?

**Review by Tryneus — APPROVED** [review]
LGTM, one nit

**Review by Tryneus — APPROVED** [review]
