### PR TITLE
Expose pipeline failures.

### LINKED ISSUE #4815: large parallelism specs make k8s hit a queries-per-second (qps) limit
Hi all - my pipeline killed in the middle with error - `Reason: pull QPS exceeded`

tried to rerun it - fail with the same error.

it do runs for several hours and then fail.

any Idea ?

---

Ticket created from a Slack message by John Karabaic (he/him) in #users. gz#29

### PR DESCRIPTION
**Pull request by jdoliner**
This PR does a few things to surface pipeline errors:

- It adds a new pipeline state "crashing" which pipelines that encounter infra errors (like unscheduled pods) enter. This state isn't terminal, so if the error resolves itself the pipeline will go into running.
- It detects the failure condition that occurs when a pod can't be scheduled. 
- It adds a count of how many pods are up for a pipeline, vs how many are expected.
- It adds a message at the top of `list pipeline` when there's a crashing or failed pipeline in the list telling users how to get more info about it.

Fixes #4815

### CODE REVIEW

File: src/server/pps/server/pipeline_controller.go [hunk 1]
```diff
@@ -145,19 +146,35 @@ func (a *apiServer) step(pachClient *client.APIClient, pipeline string, keyVer,
...
+			return op.setPipelineState(pps.PipelineState_PIPELINE_PAUSED, "")
+		}
+		workersUp, err := a.allWorkersUp(pachClient, op.pipelineInfo)
+		if err != nil {
+			return err
+		}
+		if workersUp {
+			return op.setPipelineState(pps.PipelineState_PIPELINE_RUNNING, "")
+		}
+		time.Sleep(10 * time.Second)
```
Comment (jdoliner) [inline src/server/pps/server/pipeline_controller.go:176]: I'm not totally sure about this line, it prevents the controller from busy looping when a pipeline is crashing, but I'm not sure if there's a better place to do it. At the very least I probably shouldn't be using a hard coded value here.

Comment (msteffen) [reply src/server/pps/server/pipeline_controller.go]: I think I see how this works. One alternative that occurs to me would be to spawn a goroutine, similar to `monitorPipeline`, that watches the workers and handles the transition to `RUNNING`. Instead of looping in the controller, the controller is unblocked and the loop happens separately off to the side (and the side loop is responsible for putting the pipeline into `RUNNING`, like `monitorPipeline`).

I think this would at least makes the sleep less obtrusive (and it could eventually be replaced with kubernetes watches, I think) and it removes the need to set the pipeline state to `CRASHING` which gets rid of the controller feedback loop.

File: src/server/pps/server/pipeline_controller.go [hunk 2]
```diff
@@ -145,19 +148,35 @@ func (a *apiServer) step(pachClient *client.APIClient, pipeline string, keyVer,
...
+		}
+		workersUp, err := a.allWorkersUp(pachClient, op.pipelineInfo)
+		if err != nil {
+			return err
+		}
+		if workersUp {
+			return op.setPipelineState(pps.PipelineState_PIPELINE_RUNNING, "")
+		}
+		time.Sleep(crashingBackoff)
+		return op.setPipelineState(pps.PipelineState_PIPELINE_CRASHING, op.pipelineInfo.Reason)
```
Comment (msteffen) [inline src/server/pps/server/pipeline_controller.go:179]: There's a prior response with more detail (which I can move here if it would be helpful) but I think this could be moved into a separate goro, which would shorten the amount of work done in the critical path of the controller and remove the feedback loop created by overwriting the pipeline state to `CRASHING`.

Also, it occurs to me that setting the pipeline state after a long sleep could create a race where a user updates a pipeline (putting it into `STARTING`) during the 10-second sleep, and then the new pipeline is transistioned straight into `CRASHING` when the sleep terminates, even if the new pipeline may be healthy.

File: src/server/pkg/ppsutil/util.go [hunk 3]
```diff
@@ -176,13 +176,22 @@ func GetPipelineInfo(pachClient *client.APIClient, ptr *pps.EtcdPipelineInfo) (*
...
 func FailPipeline(ctx context.Context, etcdClient *etcd.Client, pipelinesCollection col.Collection, pipelineName string, reason string) error {
+	return setPipelineState(ctx, etcdClient, pipelinesCollection, pipelineName, reason, pps.PipelineState_PIPELINE_FAILURE)
+}
+
+// CrashingPipeline updates the pipeline's state to crashing and sets the reason
+func CrashingPipeline(ctx context.Context, etcdClient *etcd.Client, pipelinesCollection col.Collection, pipelineName string, reason string) error {
+	return setPipelineState(ctx, etcdClient, pipelinesCollection, pipelineName, reason, pps.PipelineState_PIPELINE_CRASHING)
+}
+
+func setPipelineState(ctx context.Context, etcdClient *etcd.Client, pipelinesCollection col.Collection, pipelineName string, reason string, state pps.PipelineState) error {
```
[the remark this answers is not in the document]
Comment (msteffen) [reply src/server/pkg/ppsutil/util.go]: Marking this done, these should be the same now

File: src/server/pps/server/api_server.go [hunk 4]
```diff
@@ -2422,6 +2422,19 @@ func (a *apiServer) inspectPipeline(pachClient *client.APIClient, name string) (
 			pipelineInfo.GithookURL = githook.URLFromDomain(ingress.Hostname)
 		}
 	}
+
+	parallelism, err := ppsutil.GetExpectedNumWorkers(a.env.GetKubeClient(), pipelineInfo.ParallelismSpec)
```
[the remark this answers is not in the document]
Comment (msteffen) [reply src/server/pps/server/api_server.go]: Marking this done.

File: src/server/pps/server/pipeline_controller.go (hunk 2 above)
Comment (jdoliner) [reply src/server/pps/server/pipeline_controller.go:179]: That makes a lot of sense, to make sure I understand what you're saying here: This would spin off a goro that polls k8s at some interval to see if the pods are up, and if they are it would transition the state into running and exit? That sounds a lot better to me.

Comment (msteffen) [reply src/server/pps/server/pipeline_controller.go]: Yup, exactly (and you might be alluding to this already, but there's even a function, transitionPipelineState, that the goro can call to make sure there wasn't a `stopPipeline` call made while the pipeline was in `CRASHING` that would be undone by the transition to `RUNNING`)

File: src/server/pps/server/master.go [hunk 5]
```diff
@@ -421,6 +433,31 @@ func (a *apiServer) monitorPipeline(pachClient *client.APIClient, pipelineInfo *
...
+			break For
+		}
+		time.Sleep(crashingBackoff)
+		workersUp, err := op.allWorkersUp()
+		if err != nil {
+			log.Printf("error in monitorCrashingPipeline: %v", err)
+			continue
+		}
+		if workersUp {
+			if err := op.setPipelineState(pps.PipelineState_PIPELINE_RUNNING, ""); err != nil {
```
Comment (msteffen) [inline src/server/pps/server/master.go:452]: Do you think there's any way this codepath could be entered when the pipeline is in `PAUSED`? I know that `step()` cancels any `monitorCrashingPipeline` goros when it detects an update, which might be all that's needed.

If it *could* happen, then `transitionPipelineState` could be used to confirm that the pipeline is still in `CRASHING` when this is called, but I can't tell if it's necessary or not.

File: src/server/pps/server/master.go [hunk 6]
```diff
@@ -180,16 +180,28 @@ func (a *apiServer) setPipelineCrashing(ctx context.Context, pipelineName string
...
 		cancel()
 		delete(a.monitorCancels, pipeline)
 	}
-	a.monitorCancelsMu.Unlock()
+}
+
+// Every crashing pipeline has a corresponding goro running
+// monitorCrashingPipeline that checks to see if the issues have resolved
+// themselves and moves the pipeline out of crashing if they have.
+func (a *apiServer) cancelCrashingMonitor(pipeline string) {
```
Comment (msteffen) [inline src/server/pps/server/master.go:198]: I think this might need to be called in `deletePipelineResources`, so that when a pipeline is updated, leftover `cancelCrashingMonitor` goros get shut down and don't accidentally clobber the state of the updated pipeline
