### PR TITLE
In pps.GetLogs, wrap k8s RPCs in backoff loop

### LINKED ISSUE #2009: `pachctl get-logs` can miss logs
Steps to reproduce:

* I suspect any pipeline would do, but I was using this pipeline: https://github.com/Southclaws/pachyderm-parallelism-issue
* Use `pachctl get-logs` on a job.  Do it multiple times.  You can see that sometimes some logs are missing.

### PR DESCRIPTION
**Pull request by msteffen**
Also, detect k8s issue #47800 so we retry if we hit it.

Fixes #2009

### CODE REVIEW

File: src/server/pps/server/api_server.go [hunk 1]
```diff
@@ -487,22 +488,22 @@ func (a *apiServer) GetLogs(request *pps.GetLogsRequest, apiGetLogsServer pps.AP
...
 		err := a.jobs.ReadOnly(ctx).Get(request.Job.ID, &jobInfo)
 		if err != nil {
 			return fmt.Errorf("could not get job information for %s: %s", request.Job.ID, err.Error())
 		}
-
 		rcName, err = a.lookupRcNameForPipeline(ctx, jobInfo.Pipeline)
 		if err != nil {
 			return err
 		}
-	} else {
```
Comment (derekchiang) [inline src/server/pps/server/api_server.go]: Why did we remove this check?

File: src/server/pps/server/api_server.go [hunk 2]
```diff
@@ -524,49 +525,64 @@ func (a *apiServer) GetLogs(request *pps.GetLogsRequest, apiGetLogsServer pps.AP
...
 				}
-				select {
-				case errCh <- err:
-				case <-done:
+				// Occasionally, fullLogs is truncated and contains the string
+				// 'unexpected stream type ""' at the end. I believe this is a recent
+				// bug in k8s (https://github.com/kubernetes/kubernetes/issues/47800)
+				// so we're adding a special handler for this corner case.
+				// TODO(msteffen) remove this handling once the issue is fixed
+				if bytes.HasSuffix(fullLogs, []byte("unexpected stream type \"\"")) {
```
Comment (derekchiang) [inline src/server/pps/server/api_server.go]: Would it be more reliable to simply use `string.Contains()`?

File: src/server/pkg/backoff/exponential.go [hunk 3]
```diff
@@ -114,8 +127,24 @@ func NewInfiniteBackOff() *ExponentialBackOff {
...
-	return b
+	return b.withCanonicalRandomizationFactor().withReset()
+}
+
+// New10sBackoff returns a backoff that's slightly more aggressive than
+// NewExponentialBackOff. The Max Elapsed time for this backoff is 10s, and the
+// initial backoff is 100ms (instead of 500). Therefore this will retry at most
+// 11 times and then fail (depending on RPC timeout), and may be more useful
+// for interactive RPCs than the default timeout of 60s.
+func New10sBackoff() *ExponentialBackOff {
```
Comment (derekchiang) [inline src/server/pkg/backoff/exponential.go]: Seems kinda weird that we have a function specifically for 10s.  Would it be hard to simply use `NewExponentialBackoff`, and then manually set the `MaxElapsedTime` before using it?

File: src/server/pps/server/api_server.go (hunk 1 above)
Comment (msteffen) [inline src/server/pps/server/api_server.go]: It's redundant. On line 475 we already have:
```
if request.Pipeline == nil && request.Job == nil {
  return fmt.Errorf("must set either pipeline or job filter in call to GetLogs")
}
```

File: src/server/pkg/backoff/exponential.go (hunk 3 above)
Comment (msteffen) [inline src/server/pkg/backoff/exponential.go]: I adjusted InitialInterval too, since IMO 500ms backoff is also too slow for interactive RPCs.

I can move this out if you want, but there are a bunch of places where we don't retry and should, and I think we should be using this in most of them. I think I'll want to add this back at some point, if not in this PR.

If the name seems bad, I'd be happy to call it something else? NewInteractiveBackoff or something?

File: src/server/pps/server/api_server.go (hunk 2 above)
Comment (msteffen) [inline src/server/pps/server/api_server.go]: Done
