### PR TITLE
Fix master not found on put file

### LINKED ISSUE #3184: master not found error with put-file into open commit
**What happened?**:
When doing put-file into an open commit, get `master not found` error, but the file(s) still get put into the commit correctly. Haven't found any other effects other than an incorrect error message. 

```
pc list-commit images
REPO ID PARENT STARTED DURATION SIZE
JosephZckersMBP:demo joeyzwicker$ pc start-commit images master
9dd26fda14474f33bebe546b711e69ed
JosephZckersMBP:demo joeyzwicker$ pachctl put-file images master -r -f set1
pachyderm/1.7.0/pachyderm_pfs/openCommits/ master not found
JosephZckersMBP:demo joeyzwicker$ pc list-file images master
NAME TYPE SIZE
set1 dir  78.7KiB
```

**What you expected to happen?**:
No error message since everything seems to be working fine

**How to reproduce it (as minimally and precisely as possible)?**:
above
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
pachctl 1.7.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

### PR DESCRIPTION
**Pull request by ysimonson**
Fixes #3184

### CODE REVIEW

**Comment by ysimonson** [comment]
As an aside, is this note still relevant? If not I can remove it as part of this PR: https://github.com/pachyderm/pachyderm/blob/29e5f110e8759bb3a2f03161c327c667d0874b9d/src/server/pfs/cmds/cmds.go#L669-L672

File: src/server/pfs/server/driver.go [hunk 1]
```diff
@@ -3310,28 +3285,76 @@ func (s *putFileServer) Peek() (*pfs.PutFileRequest, error) {
...
+					if branch == "" {
+						err = pfsserver.ErrCommitFinished{commit}
+						return oneOff, repo, branch, err
+					}
+					oneOff = true
+				}
+				commitID = commit.ID
+			} else if req.File.Commit.ID != rawCommitID {
+				err = fmt.Errorf("All requests in a put files call must have the same commit ID; expected '%s', got '%s'", rawCommitID, req.File.Commit.ID)
+				return oneOff, repo, branch, err
```
Comment (msteffen) [inline src/server/pfs/server/driver.go]: I'm not sure if this would break `putFiles`, but would it make sense to return `false, "", "", err` here (and in error cases below)? My impression is that it's more conventional in go to discard other return values when returning an error.

File: src/server/pfs/server/driver.go [hunk 2]
```diff
@@ -3310,28 +3285,76 @@ func (s *putFileServer) Peek() (*pfs.PutFileRequest, error) {
...
+				// subsequent requests use the same value.
+				rawCommitID = commit.ID
+				// oneOff is true if we're creating the commit as part of this put-file
+				oneOff = false
+				// inspectCommit will replace file.Commit.ID with an actual commit ID if
+				// it's a branch. So we want to save it first.
+				if !uuid.IsUUIDWithoutDashes(commit.ID) {
+					branch = commit.ID
+				}
+				commitInfo, err := d.inspectCommit(pachClient, commit, pfs.CommitState_STARTED)
```
Comment (msteffen) [inline src/server/pfs/server/driver.go]: Would you be on board with adding a comment here like:
```
// inspect the commit where we're adding files and figure out if this
// is a one-off put-file. 
// - if 'commit' refers to an open commit                -> not oneOff
// - otherwise (i.e. branch with closed HEAD or no HEAD) -> yes oneOff
// Note that if commit is a specific commit ID, it must be open for
// this call to succeed
```
Just because the code here is doing a lot, but I think the question it's answering is pretty short

**Comment by msteffen** [comment]
> As an aside, is this note still relevant?

I think it would be totally fine to kill that note

**Comment by msteffen** [comment]
Reassigning to myself, since I basically just reviewed this, and I think we only need one review

File: src/server/pfs/server/driver.go [hunk 3]
```diff
@@ -3310,28 +3285,78 @@ func (s *putFileServer) Peek() (*pfs.PutFileRequest, error) {
...
+			} else if req.File.Commit.ID != rawCommitID {
+				err = fmt.Errorf("All requests in a put files call must have the same commit ID; expected '%s', got '%s'", rawCommitID, req.File.Commit.ID)
+				return false, "", "", err
+			} else if req.File.Commit.Repo.Name != repo {
+				err = fmt.Errorf("All requests in a put files call must have the same repo name; expected '%s', got '%s'", repo, req.File.Commit.Repo.Name)
+				return false, "", "", err
+			} else {
+				req.File.Commit.ID = commitID
+			}
+
```
[the remark this answers is not in the document]
Comment (ysimonson) [reply src/server/pfs/server/driver.go]: In the old implementation, we were peeking the first put file request and dereferencing its commit ID, but not doing so for subsequent requests. As a result, on an open commit to a branch, the first file in a put file request would go through (because the commit ID was dereferenced), but not subsequent requests.

With this change, the first put file request's commit ID is still dereferenced, but we now update subsequent requests to use the dereferenced commit ID.

File: src/server/pfs/server/driver.go [hunk 4]
```diff
@@ -3441,16 +3443,17 @@ func (d *driver) forEachPutFile(pachClient *client.APIClient, server pfs.API_Put
...
+		// simply calling Close()
 		pw.CloseWithError(err) // can't error
 	}
 	if err != io.EOF {
-		return oneOff, repo, branch, err
+		return false, "", "", err
 	}
 	err = eg.Wait()
-	return oneOff, repo, branch, err
+	return false, "", "", err
```
Comment (msteffen) [inline src/server/pfs/server/driver.go]: Should this return statement keep the old parameters? i.e. `return oneOff, repo, branch, nil`. Or is this an error  too?

Comment (ysimonson) [reply src/server/pfs/server/driver.go]: that would explain why my test is failing, heh
