### PR TITLE
Fix skipped datums correctness

### LINKED ISSUE #2152: Fix correctness issue w skipped datum status
Right now if you have 3 commits:

commit1 - add file foo
commit2 - delete file foo
commit3 - add file foo again

The datum corresponding to file foo on the 3rd commit will show it as success (because it shows up in the diff btw commit2 and commit3), even though it should be marked as skipped (as it was processed in commit1).

Instead, we'll write a `skipped` file like we do for failures, but do it on the worker master so that we don't incur round trips to obj storage for every skipped datum.

### PR DESCRIPTION
**Pull request by sjezewski**
fixes #2152

### CODE REVIEW

File: src/server/pachyderm_test.go [hunk 1]
```diff
@@ -3775,6 +3775,98 @@ func TestPipelineWithStatsAcrossJobs(t *testing.T) {
...
+func TestPipelineWithStatsSkippedEdgeCase(t *testing.T) {
+	// If I add a file in commit1, delete it in commit2, add it again in commit 3 ...
+	// the datum will be marked as success on the 3rd job, even though it should be marked as skipped
+	if testing.Short() {
+		t.Skip("Skipping integration tests in short mode")
+	}
+	t.Parallel()
+	c := getPachClient(t)
+
+	dataRepo := uniqueString("TestPipelineWithStats_data")
```
Comment (jdoliner) [inline src/server/pachyderm_test.go]: This name references a different test.

File: src/server/pps/server/api_server.go [hunk 2]
```diff
@@ -582,49 +582,29 @@ func (a *apiServer) getDatum(ctx context.Context, repo string, commit *pfs.Commi
...
-		return nil, err
-	}
-	// Datum wasn't added in this commit, so it was skipped
-	if len(resp.NewFiles) == 0 {
+	_, err = pfsClient.InspectFile(ctx, &pfs.InspectFileRequest{stateFile})
+	if err == nil {
+		datumInfo.State = pps.DatumState_SKIPPED
+		// Datum wasn't added in this commit, so it was skipped
 		return datumInfo, nil
+	} else if !strings.Contains(err.Error(), "not found") {
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: There should be a helper somewhere that you can use for this. If not it's probably worth it to add one to this file for the one below as well?

File: src/server/worker/master.go [hunk 3]
```diff
@@ -409,11 +409,14 @@ func (a *APIServer) runJob(ctx context.Context, jobInfo *pps.JobInfo, pool *pool
 		}
 		tree := hashtree.NewHashTree()
 		var statsTree hashtree.OpenHashTree
+		var skippedTree hashtree.OpenHashTree
```
Comment (jdoliner) [inline src/server/worker/master.go]: I think I told you to implement it this way with an extra tree... but looking at it now I think you could just drop `skippedTree` and anywhere and use `statsTree` in its place. That way there's also no need to `Merge` since you're writing the files to the place they should ultimately go to.

**Comment by sjezewski** [comment]
I think I've addressed all the feedback, please take another look @jdoliner
