### PR TITLE
Fix issue where bad datums didn't always fail jobs

### LINKED ISSUE #4151: successful job doesn't process 4/5 datums that it should have
**What happened?**:

A job ran on 5 input datums which should have produced 5 output datums.  
Only 1 output datum was produced.
Logs show errors and retries processing the missing datums.

**What you expected to happen?**:

All 5 datums successfully processed, or the job failed if the datums were not processed successfully.

**How to reproduce it (as minimally and precisely as possible)?**:

Not yet reproducible.

User kibana logs are available here:

https://drive.google.com/open?id=1MI2fQLawT0Pr6b6voCtgmEd85sNapiL7

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

### PR DESCRIPTION
**Pull request by msteffen**
The fix is the new return statement in `worker/master.go`. The change in `ppsutil` is explained at the bottom.

The reason that this bug occurred so rarely is that is the goro (spawned [here](https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/master.go#L441 )) calls `cancel()` as soon as the job's output commit is finished with no tree. Then one of the operations in `waitJob` after line 695 (e.g. [PutObject](https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/master.go#L706)) typically fails with `context cancelled` and the backoff handler exits at [ctx.Done()](https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/master.go#L736). However, rarely, the goro might be too slow to call `cancel()` and then `waitJob` makes it all the way to [updateJobState(SUCCESS)](https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/master.go#L732) at the end, overwriting the `FAILURE` state the the job was previously in.

This bug can be exposed by adding a sleep [right before cancel() is called](https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/master.go#L479) (inside a defer). This is how I tested the fix manually.

Finally, I also changed `UpdateJobState` so that jobs can't be taken out of `FAILURE` once they've been put into failure, a rule we already enforce [with pipelines](https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/server/master.go#L255)

Fixes #4151

### CODE REVIEW

File: src/server/worker/master.go [hunk 1]
```diff
@@ -692,6 +692,7 @@ func (a *APIServer) waitJob(pachClient *client.APIClient, jobInfo *pps.JobInfo,
 			}); err != nil && !pfsserver.IsCommitFinishedErr(err) {
 				return err
 			}
+			return nil
```
Comment (jdoliner) [inline src/server/worker/master.go]: I could be wrong but I think we still want to do some of the stuff below this when there's a failed job. Such as writing out the datums object. @brycemcanally can clarify.

Comment (brycemcanally) [reply src/server/worker/master.go]: We should be returning here, this is correct. The path @msteffen described is intended for killing a job not a failed datum, it just so happens that it would cancel the ctx (because the commit would be finished) and would work out correctly some (I guess most?) of the time. I introduced this issue when making the short term job logic changes because I added the logic for not considering the finished commit error and accidentally did not keep a return here.

File: src/server/pkg/ppsutil/util.go [hunk 2]
```diff
@@ -390,6 +390,10 @@ func IsTerminal(state pps.JobState) bool {
 
 // UpdateJobState performs the operations involved with a job state transition.
 func UpdateJobState(pipelines col.ReadWriteCollection, jobs col.ReadWriteCollection, jobPtr *pps.EtcdJobInfo, state pps.JobState, reason string) error {
+	if jobPtr.State == pps.JobState_JOB_FAILURE {
```
Comment (brycemcanally) [inline src/server/pkg/ppsutil/util.go]: I'm not sure if this is a good idea. It seems like it could mask bugs? I mean, I guess it is good to keep the job in a failed state if it was marked as failed before, but we would not know about the issue we found if this existed. The side effects from what you fixed (uploading a datums object, attempting egress, etc.) would go unnoticed without the job state indicating an issue.

Comment (msteffen) [reply src/server/pkg/ppsutil/util.go]: I don't feel strongly about keeping this. An alternative would be to return an error if the job is in FAILURE? That might actually have made the bug apparent earlier.

@jdoliner?

Comment (jdoliner) [reply src/server/pkg/ppsutil/util.go]: Returning an error here seems like the right call.
