### PR TITLE
Make it possible to run pachyderm without exposing the docker socket.

### LINKED ISSUE #2813: Pachyderm worker should not need access to host Docker socket
**What is the ask?**

I need a roadmap that arrives at pachyderm workers not mounting the host Docker socket. Our Kubernetes clusters are multi-tenant and therefore access to the host Docker socket is extremely limited.

**What is the goal / desired outcome?**

So that I can accomplish my goal of using Pachyderm within my organization's security mandate.

**If there is a way to accomplish this today via workaround, what does that require?**

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.8.x
- Pachyderm CLI version (use `pachctl version`): 1.6.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): all
- OS (e.g. from /etc/os-release): N/A
- Others:

**What happened?**:

The Pachyderm worker mounts the host Docker socket in order to describe the user's container (and thereby discover the entry point, working dir, and UID/GID.

**What you expected to happen?**:

No mounting of the host Docker socket.

**How to reproduce it (as minimally and precisely as possible)?**:

Launch a pipeline. Inspect the created Pods.

**Anything else we need to know?**:

This is clearly by design. The request is for a path to an unprivileged worker. 

One option may be to state in the pipeline definition the information currently discovered via the Docker socket. This would allow configuring pipelines without using the socket, which in turn would allow creating a feature to disable use of the socket.

### PR DESCRIPTION
**Pull request by jdoliner**
Fixes #2813

### CODE REVIEW

File: src/server/cmd/pachd/main.go [hunk 1]
```diff
@@ -84,6 +84,7 @@ type appEnv struct {
 	LogLevel              string `env:"LOG_LEVEL,default=info"`
 	IAMRole               string `env:"IAM_ROLE,default="`
 	ImagePullSecret       string `env:"IMAGE_PULL_SECRET,default="`
+	NoExposeDockerSocket  bool   `env:"NO_EXPOSE_DOCKER_SOCKET,default=false"`
```
Comment (msteffen) [inline src/server/cmd/pachd/main.go]: would it make sense to make this `EXPOSE_DOCKER_SOCKET` with the default set to `true`? Then you could have `if exposeDockerSocket` rather than `if !noExposeDockerSocket` later on

File: src/server/worker/api_server.go [hunk 2]
```diff
@@ -330,30 +329,37 @@ func NewAPIServer(pachClient *client.APIClient, etcdClient *etcd.Client, etcdPre
...
+			pipelineInfo.Transform.User = image.Config.User
+		}
+		if pipelineInfo.Transform.WorkingDir == "" {
+			pipelineInfo.Transform.WorkingDir = image.Config.WorkingDir
+		}
+		if server.pipelineInfo.Transform.Cmd == nil {
+			server.pipelineInfo.Transform.Cmd = image.Config.Entrypoint
+		}
+	}
+	fmt.Printf("user: %s\n", pipelineInfo.Transform.User)
```
Comment (msteffen) [inline src/server/worker/api_server.go]: leftover debug statement? Or do we want this?

File: src/server/cmd/pachd/main.go (hunk 1 above)
Comment (jdoliner) [reply src/server/cmd/pachd/main.go]: I can definitely see the logic for that, I did it this way because throughout the code base `bool` values always default to `false` since that's what go naturally defaults them to and so we invert a lot of conditions so that the default value of `false` corresponds to the behavior we think makes for a better default. In this case it doesn't really make sense for this struct, but I think it does make sense for the feature as a whole, because the flag to enable it at deploy time is `--no-expose-docker-socket` if the flag was `--expose-docker-socket` with a default of true, then the only use for the flag would be `--expose-docker-socket=false` which I think is a little more confusing. This is pretty hairsplitty though.

File: src/server/worker/api_server.go (hunk 2 above)
Comment (jdoliner) [reply src/server/worker/api_server.go]: Yup, good catch, removed.
