### PR TITLE
Configure `pach-dir-volume` for openshift

### LINKED ISSUE #3404: sidecar tries to create /pach dir; fails without root access
When trying to create a pipeline while running the worker and sidecar without root access yields:

```
$ oc logs pod/pipeline-edges-v1-jq62f -c user
time="2019-01-25T19:42:53Z" level=warning msg="skipping "/pach-bin/certs/ca-certificates.crt", could not create output file "/etc/ssl/certs/ca-certificates.crt": open /etc/ssl/certs/ca-certificates.crt: permission denied" 
time="2019-01-25T19:42:53Z" level=warning msg="Errors were encountered while copying /pach-bin/certs to /etc/ssl/certs (see above--might result in subsequent SSL/TLS errors)" 
error getting pipelineInfo: could not read existing PipelineInfo from PFS: mkdir /pach: permission denied
$ oc logs pod/pipeline-edges-v1-jq62f -c storage
2019-01-25T16:48:49Z INFO authclient.API.WhoAmI {"request":{}} []
2019-01-25T16:48:49Z INFO authclient.API.WhoAmI {"request":{}} []
2019-01-25T16:48:49Z INFO authclient.API.WhoAmI {"request":{}} []
2019-01-25T16:48:49Z INFO authclient.API.WhoAmI {"request":{}} []
2019-01-25T16:48:49Z ERROR pfs.API.GetFile {"duration":0.006057808,"error":"mkdir /pach: permission denied","request":{"file":{"commit":{"repo":{"name":"__spec__"},"id":"65817ae7da884f2e8c5c6c490ac9bfc0"},"path":"spec"}}} []
```

The certs issue is addressed in #3394, but appears to be non-fatal. the real issue seems to be that the sidecar is failing due to not being able to create the `/pach` dir

currently working around the issue by manually mounting an `emptyDir` volume at `/pach`. This seems to be working, so should be rolled into the pachd-generated pipeline RC manifest 

Specifically, I've added

```
            - mountPath: /pach
              name: pach-dir-volume
```
To the `storage` container's `volumeMounts` in the pipeline RC's template spec, which seems to be defined here: https://github.com/pachyderm/pachyderm/blob/9b5949f3d0850009ed852d311384f1b1bd5fb25e/src/server/pps/server/worker_rc.go#L99

and added an extra volume to the pipeline RC's template spec:

```
      volumes:
        - emptyDir: {}
          name: pach-dir-volume
...
```
which seems to be defined here: https://github.com/pachyderm/pachyderm/blob/9b5949f3d0850009ed852d311384f1b1bd5fb25e/src/server/pps/server/worker_rc.go#L98

AFACT this could just be made a permanent change in all deployments, rather than having this configurable by env var, but we do need to take account of the fact that there is already an env var that points at this location:

```
            - name: PACH_ROOT
              value: /pach
```

This probably means i could be changing that env var to point at somewhere writable, rather than creating the volume, but as a permanent fix, i'm not sure what location we'd want to point that is always going to be writable (unless we create a world-writable dir in the container as part of the image build, as suggested here: https://docs.okd.io/latest/creating_images/guidelines.html#use-uid )

### PR DESCRIPTION
**Pull request by ysimonson**
Fixes #3404

~~Further development on hold, because @jdoliner is taking a deeper look on why this might be needed in the first place. @jdoliner let me know if/when I should resume work on this.~~

### CODE REVIEW

File: src/server/pps/server/worker_rc.go [hunk 1]
```diff
@@ -95,8 +95,18 @@ func (a *apiServer) workerPodSpec(options *workerOptions) (v1.PodSpec, error) {
...
+	options.volumes = append(options.volumes, secretVolume, v1.Volume{
+		Name: "pach-dir-volume",
+		VolumeSource: v1.VolumeSource{
+			EmptyDir: &v1.EmptyDirVolumeSource{},
+		},
+	})
+	sidecarVolumeMounts = append(sidecarVolumeMounts, secretMount, v1.VolumeMount{
+		Name:      "pach-dir-volume",
+		MountPath: a.storageRoot,
+	})
```
Comment (jdoliner) [inline src/server/pps/server/worker_rc.go]: Playing around with this on my machine I get the following when I try to run `TestSimplePipeline`:

```
error running the master process: ReplicationController "pipeline-testsimplepipelinec5ed94a91679-v1" is invalid: spec.template.spec.containers[1].volumeMounts[2].mountPath: Invalid value: "/pach": must be unique; retrying in 3.6971187s"
```

Which makes sense because in local deployments we put a hostpath mount there, so we get an overlap. The place where we do this is a few lines above (starts on 81), I think if you put this in an `else` block for that conditional it would pass CI. There's still the open question as to where that `MkdirAll` is coming from that's creating the error. I did some more checking and can't figure it out. It might be a good idea to run a binary with a `runtime.PrintBacktrace()` call next to the error handling for that `MkdirAll` just so we can see the execution path that's leading to it.
