### PR TITLE
Fix bug in 'pachctl edit pipeline' and make --raw and --output description and usage consistent

### LINKED ISSUE #4510: pachctl edit pipeline is opening an empty file after using pachctl run cron to trigger input cron pipeline
**What happened?**:

Pachyderm version 1.9.7 edits correctly.
Trying with pachyderm version 1.9.10 and 1.9.11 binaries of pachctl, the command open the editor empty and the text is displayed in stdout after leaving the editor.

**What you expected to happen?**:
Execute: `pachctl edit pipeline extraction`
Open the editor with the pipeline definition content and be able to edit and update as in version 1.9.7.

**How to reproduce it (as minimally and precisely as possible)?**:
Tried with pachctl server version 1.9.10 and 1.9.11, created an input cron pipeline and tried to edit.

The pipeline is as follows, just replaced the docker images and buckets:

```
{
  "pipeline": {
    "name": "extraction"
  },
  "transform": {
    "image": "AWSACCOUNT.dkr.ecr.eu-west-1.amazonaws.com/IMAGE:TAG",
    "env": {
      "ENVIRONMENT": "staging",
      "AWS_ATHENA_S3_STAGING_DIR": "s3://aws-athena-query-results-AWSACCOUNT/",
      "AWS_DEFAULT_REGION": "AWSREGION"
    },
    "cmd": ["python","extraction.py","--output_path","/pfs/out","--max_rows", "100000000"]
  },
  "input": {
    "cron": {
      "name": "morning",
      "spec": "40 2 * * *",
      "overwrite": true
    }
  },
 "output_branch": "master",
  "egress": {
    "URL": "s3://OUT/"
  }
}
```

**Anything else we need to know?**:
Pipeline was created with client and server version 1.9.10

**Environment?**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
COMPONENT           VERSION
pachctl             1.9.11
pachd               1.9.11

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
AWS

- OS (e.g. from /etc/os-release):
Linux and Mac

### PR DESCRIPTION
**Pull request by msteffen**
Fix #4510

### CODE REVIEW

File: src/server/pps/cmds/cmds.go [hunk 1]
```diff
@@ -734,6 +741,11 @@ All jobs created by a pipeline will create commits in the pipeline's output repo
 			// validate flags
 			if raw && spec {
 				return fmt.Errorf("cannot set both --raw and --spec")
+			} else if !raw && !spec && output != "" {
+				fmt.Fprintln(os.Stderr, "-------------------------------")
+				fmt.Fprintf(os.Stderr, "output: %q\n", output)
+				fmt.Fprintln(os.Stderr, "-------------------------------")
```
Comment (Tryneus) [inline src/server/pps/cmds/cmds.go]: Are these first three messages really necessary?

Comment (msteffen) [reply src/server/pps/cmds/cmds.go]: :man_facepalming: This is debugging code. I meant to remove this.

I'll check and see if I left anything else in, but thanks!
