### PR TITLE
Fix update pipeline

### LINKED ISSUE #1029: update-pipeline sometimes fails
The issue is that we have a `parentJob` function in PPS that finds the parent job for a job.  It does that by:

1. Compute the input commits of the parent job
2. Find the job that has the said input commits

However, this function doesn't consider the fact that there can be more than one jobs that have the same set of input commits, which happens when you have updated a pipeline.  Therefore in step 2, `parentJob` might find more than one jobs that have the "parent input commits", and end up using the wrong job as the parent, which eventually leads to the new pipeline failing to start new jobs.

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #1029

### CODE REVIEW

File: src/server/pps/server/api_server.go [hunk 1]
```diff
@@ -1737,10 +1742,12 @@ func (a *apiServer) parentJob(
 	if err != nil {
 		return nil, err
 	}
-	if len(jobInfo.JobInfo) == 0 {
-		return nil, nil
+	for _, jobInfo := range jobInfos.JobInfo {
+		if jobInfo.PipelineVersion == pipelineInfo.Version {
+			return jobInfo.Job, nil
+		}
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: Does it make sense to have this filtering be part of the `ListJobRequest` so that it can be done efficiently on the server?

**Comment by jdoliner** [comment]
One small question. But not strictly necessary for merge.
nine-and-watch

File: src/server/pps/server/api_server.go (hunk 1 above)
Comment (derekchiang) [inline src/server/pps/server/api_server.go]: That would make sense, but then you'd have to create a `PipelineVersion` message because you need a way to signify that you don't care about the version.  And `0` won't do because 0 is a valid version number.

How about let's do that when we have other code that needs to filter jobs by pipeline version.  Right now only this `parentJob` function does that.

Comment (jdoliner) [inline src/server/pps/server/api_server.go]: Sounds reasonable.
