### PR TITLE
Fixed flag help/error messaging when pushing images

### LINKED ISSUE #3350: `--push-images` failing
When using `pachctl update-pipeline --push-images`, I'm getting the error: `API error (500): {"message":"invalid reference format"}`. As far as I can see, the pipeline (and repo spec) is valid:

```
{
  "pipeline": {
    "name": "edges"
  },
  "input": {
    "atom": {
      "glob": "/*",
      "repo": "images"
    }
  },
  "transform": {
    "cmd": [ "python3", "/edges.py" ],
    "image": "ysimonson/opencv"
  }
}
```

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```
COMPONENT           VERSION                                          
pachctl             1.8.2-29e5f110e8759bb3a2f03161c327c667d0874b9d   
pachd               1.8.2-29e5f110e8759bb3a2f03161c327c667d0874b9d  
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube
- OS (e.g. from /etc/os-release): macOS
- Others:

### PR DESCRIPTION
**Pull request by ysimonson**
This fixes two issues related to `--push-images`:

1) The flag help for username incorrectly says that it defaults to the OS username, but this was [changed recently](https://github.com/pachyderm/pachyderm/pull/3322)
2) The suggested [remedial steps](https://github.com/pachyderm/pachyderm/issues/3293#issuecomment-448012383) for fixing `--push-images` on macOS turns out not to work. When docker restarts, it wipes out the changes. And some [new issue](https://github.com/pachyderm/pachyderm/issues/3350) has cropped up that's related.

Fixes #3350

### CODE REVIEW

File: src/server/pps/cmds/cmds.go [hunk 1]
```diff
@@ -479,7 +479,7 @@ All jobs created by a pipeline will create commits in the pipeline's repo.
 	createPipeline.Flags().StringVarP(&pipelinePath, "file", "f", "-", "The file containing the pipeline, it can be a url or local file. - reads from stdin.")
 	createPipeline.Flags().BoolVarP(&pushImages, "push-images", "p", false, "If true, push local docker images into the cluster registry.")
 	createPipeline.Flags().StringVarP(&registry, "registry", "r", "docker.io", "The registry to push images to.")
-	createPipeline.Flags().StringVarP(&username, "username", "u", "", "The username to push images as, defaults to your OS username.")
+	createPipeline.Flags().StringVarP(&username, "username", "u", "", "The username to push images as, defaults to your docker username.")
 	createPipeline.Flags().StringVarP(&password, "password", "", "", "Your password for the registry being pushed to.")
```
Comment (gabrielgrant) [inline src/server/pps/cmds/cmds.go]: Small nit: we should probably be prompting for password interactively by default, rather than asking people to input it as part of the command

**Comment by gabrielgrant** [comment]
Oh, looks like that has already been filed here: https://github.com/pachyderm/pachyderm/issues/2395

Now that we're recommending this, though, may make sense to prioritize that change (tbh didn't even know those flags existed until now)
