### PR TITLE
Fixes #428

### LINKED ISSUE #428: get-file with a nonexistent commit should report that commit does not exist
Right now it outputs an error message like `rpc error: code = 2 desc = diff sum2/6a6d6d48860b482fae28bcc456ee0d76/19 not found`

### PR DESCRIPTION
**Pull request by sjezewski**
Updated the commit error message when GetFile() is called w an invalid commit. Now we return 'commit not found'

This error message is also sanitized when used via the CLI:

```shell
$ pachctl get-file foo sdflkjsdfkj file
commit not found
```

### CODE REVIEW

File: src/server/pfs/drive/driver.go [hunk 1]
```diff
@@ -947,7 +947,7 @@ func (d *driver) inspectFile(file *pfs.File, filterShard *pfs.Shard, shard uint6
 	for commit != nil && (from == nil || commit.ID != from.ID) {
 		diffInfo, ok := d.diffs.get(client.NewDiff(commit.Repo.Name, commit.ID, shard))
 		if !ok {
-			return nil, nil, fmt.Errorf("diff %s/%s/%d not found", commit.Repo.Name, commit.ID, shard)
+			return nil, nil, pfsserver.ErrCommitNotFound
```
Comment (derekchiang) [inline src/server/pfs/drive/driver.go]: Seems like we are losing information here by making this change.  Can we make ErrCommitNotFound a struct that contains repo name, commit ID, and shard, and implement the error interface so it can be used as an error?

Comment (derekchiang) [inline src/server/pfs/drive/driver.go]: Also just to be consistent, we probably want to use ErrCommitNotFound in other places where we are returning custom error messages for when commits are not found.  For instance: the inspectCommit() function

Comment (sjezewski) [inline src/server/pfs/drive/driver.go]: So the info we're losing is repo / commit ID / shard. When invoking GetFile() you provide the repo and commit ID, so it seemed redundant to provide this in the error message. Presumably the caller has enough information to debug.

As long as the other places we return 'commit not found' also have those inputs, I think it's fine to omit. 

But - is the shard number meaningful to report? Maybe for debugging? For the CLI, I'd say no. For the error reported to the client, I think its fine to include.

I will go through the other locations we want to return 'commit not found' and use the canonical err.

Comment (sjezewski) [inline src/server/pfs/drive/driver.go]: Ok talking w this more, we will report all the info in all the cases.

I'll use this opportunity to make the error reporting more consistent across the board. We still have some error strings in lieu of using the preset errors. And we don't have errors for missing job / etc.

File: src/server/pfs/pfs.go [hunk 2]
```diff
@@ -1,14 +1,51 @@
...
+	return &ErrCommitNotFound{
+		error: grpc.Errorf(codes.NotFound, "commit %v not found in repo %v", commitID, repo),
+	}
+}
+
+func NewErrParentCommitNotFound(repo string, commitID string) *ErrParentCommitNotFound {
+	return &ErrParentCommitNotFound{
+		error: grpc.Errorf(codes.NotFound, "parent commit %v not found in repo %v", commitID, repo),
+	}
+}
```
Comment (jdoliner) [inline src/server/pfs/pfs.go]: Will these errors get returned by the golang API? If so does it maybe make sense to put them in `src/client` so people can use them there?

File: src/client/pfs.go [hunk 3]
```diff
@@ -543,6 +566,7 @@ func (w *putFileWriteCloser) Write(p []byte) (int, error) {
 
 func (w *putFileWriteCloser) Close() error {
 	_, err := w.putFileClient.CloseAndRecv()
+	err = sanitizeErr(err)
 	return err
 }
```
Comment (jdoliner) [inline src/client/pfs.go]: Could you just inline the `sanitizeErr` calls? Storing it in a variable each time seems like a pretty big waste of vertical space.

Comment (sjezewski) [inline src/client/pfs.go]: Yup will do

File: src/server/pfs/server/internal_api_server.go [hunk 4]
```diff
@@ -104,7 +103,8 @@ func (a *internalAPIServer) DeleteRepo(ctx context.Context, request *pfs.DeleteR
 	if err != nil {
 		return nil, err
 	}
-	if err := a.driver.DeleteRepo(request.Repo, shards); err != nil && err != pfsserver.ErrRepoNotFound {
+	_, isErrRepoNotFound := err.(*pfsserver.ErrRepoNotFound)
+	if err := a.driver.DeleteRepo(request.Repo, shards); err != nil && !isErrRepoNotFound {
```
Comment (jdoliner) [inline src/server/pfs/server/internal_api_server.go]: Do these lines make sense. Isn't the error you're checking on line 106 guaranteed to be `nil` when you reach there?

Comment (jdoliner) [inline src/server/pfs/server/internal_api_server.go]: Also it's really weird to me to have the bool returned by a type check not be called `ok`

Comment (sjezewski) [inline src/server/pfs/server/internal_api_server.go]: Yup, logical error there.

I think the name is more descriptive, but thats just a style thing. I'll change it.

File: src/client/pfs.go (hunk 3 above)
Comment (sjezewski) [inline src/client/pfs.go]: Done

File: src/server/pfs/server/internal_api_server.go (hunk 4 above)
Comment (sjezewski) [inline src/server/pfs/server/internal_api_server.go]: Done and renamed in all cases

**Comment by sjezewski** [comment]
Also realized this fixed #416

**Comment by jdoliner** [comment]
9fb4586d-7c46-8143-9403-53185b1bc7ae
