### PR TITLE
Error message fixes

### LINKED ISSUE #2781: Strange Duplicate Pipeline Name Error Message in 1.7
Create a pipeline named "test2" when such a pipeline already exists

`Failed to create pipeline "test2": pipeline spec branch for "test2" already exists: delete it with DeletePipeline%!(EXTRA string=spec)`

### PR DESCRIPTION
**Pull request by jdoliner**
fixes #2781

### CODE REVIEW

File: src/server/worker/api_server.go [hunk 1]
```diff
@@ -400,13 +400,17 @@ func (a *APIServer) downloadGitData(pachClient *client.APIClient, dir string, in
 	return nil
 }
 
-func (a *APIServer) downloadData(pachClient *client.APIClient, logger *taggedLogger, inputs []*Input, puller *filesync.Puller, parentTag *pfs.Tag, stats *pps.ProcessStats, statsTree hashtree.OpenHashTree, statsPath string) (string, error) {
+func (a *APIServer) downloadData(pachClient *client.APIClient, logger *taggedLogger, inputs []*Input, puller *filesync.Puller, parentTag *pfs.Tag, stats *pps.ProcessStats, statsTree hashtree.OpenHashTree, statsPath string) (_ string, retErr error) {
 	defer func(start time.Time) {
 		stats.DownloadTime = types.DurationProto(time.Since(start))
 	}(time.Now())
-	logger.Logf("input has not been processed, downloading data")
+	logger.Logf("starting to downloading data")
```
Comment (dwhitena) [inline src/server/worker/api_server.go]: "starting to download data"
