### PR TITLE
Fix rethink init race

### LINKED ISSUE #1087: Intermittent test db errors
It seems like successfully creating a rethink DB doesn't mean its ready for table creation. The table below exists if I look at the rethink UI. 

This happens everytime I run the tests locally (local docker), so blocks me from running the tests locally.

```
--- FAIL: TestReplayMergeDiffOrdering (0.04s)
panic: gorethink: Database `pachyderm_test_c5b9e90a1920` does not exist. in: 
r.DB("pachyderm_test_c5b9e90a1920").TableCreate("Repos", primary_key="Name") [recovered]
	panic: gorethink: Database `pachyderm_test_c5b9e90a1920` does not exist. in: 
r.DB("pachyderm_test_c5b9e90a1920").TableCreate("Repos", primary_key="Name")
```

### PR DESCRIPTION
**Pull request by sjezewski**
Fixes #1087 

With this change I can run the tests locally

### CODE REVIEW

**Comment by jdoliner** [comment]
This doesn't strike me as the simplest solution to this problem. Afaict you're creating a table with a random uuid and exponential backoff on the creation process because it might fail then deleting the table and proceeding to create the new tables under the assumption that they're now guaranteed to create successfully. I see a couple of issues with this:

- if the process dies in the middle we'll be left with a bogus uuid table, not the end of the world but a little bit annoying.
- the assumption that after the first table creation is finished all future ones will succeed is true under normal operation but in some cases won't be

Why don't you just put the retry code around the real table creations? Those are the things you actually want to unsure get created right? Why ensure that a different table gets created then delete it and assume that the things you actually care about are going to succeed?

**Comment by sjezewski** [comment]
Good points all.

This code evolved from playing w rethink in different ways to see if there was another call (e.g. if we could read the table list from the db) we could use as a proxy for 'database readiness', but there's no substitute for the real thing. 

Will make these changes.

**Comment by sjezewski** [comment]
Ok, ready for another look @jdoliner

File: src/server/pfs/db/driver.go [hunk 1]
```diff
@@ -125,13 +126,34 @@ func initDB(session *gorethink.Session, dbName string) error {
...
+	tablesToInitialize := make([]Table, len(tables))
+	copy(tablesToInitialize, tables)
+	backoff.RetryNotify(func() error {
+		// Create tables
+		for i, table := range tablesToInitialize {
+			tableCreateOpts := tableToTableCreateOpts[table]
+			if _, err := gorethink.DB(dbName).TableCreate(table, tableCreateOpts...).RunWrite(session); err != nil {
+				return err
+			}
+			tablesToInitialize = append(tablesToInitialize[:i], tablesToInitialize[i+1:]...)
```
Comment (jdoliner) [inline src/server/pfs/db/driver.go]: This line seems pretty dubious to me. I'm pretty sure this will encounter a bounds error won't it? This example hits a bounds error and seems pretty equivalent: https://play.golang.org/p/3xh6kad7An On the other hand CI is passing, which gives me pause since it suggests that maybe this code isn't being run? How big is `tables` here? The bounds error won't manifest is `len(tables) <= 1` but I'm pretty sure it's bigger than that isn't it? I could just be wrong about this being a bounds error... but like I said my example seems pretty identical.

The problem here is that you're trying to wrap the creation of __all__ the tables in a single retry loop which means you need to keep track of what you accomplished in previous attempts. Instead just wrap each `TableCreate` in its own retry loop. This should be the same amount of code just moved around a little and no need for list splicing.

**Comment by sjezewski** [comment]
Yea, that was a very silly mistake. Of course the slice changes over loop iterations.

It was working by coincidence.

https://play.golang.org/p/VFFsEJdyfD

Notice that on the second and third iteration I get the same value for `val`. Then it would error because that table didn't exist, and the backoff function would get called again w just `[Commits]` for the value for `tablesToInitialize`

I'm not sure tbh why the loop behaves that way. It makes sense to me why the second value would be '3', but not why the 3rd value would be '3'.

File: src/server/pfs/db/driver.go [hunk 2]
```diff
@@ -125,12 +126,28 @@ func initDB(session *gorethink.Session, dbName string) error {
...
 	for _, table := range tables {
-		tableCreateOpts := tableToTableCreateOpts[table]
-		if _, err := gorethink.DB(dbName).TableCreate(table, tableCreateOpts...).RunWrite(session); err != nil {
+		backoff.RetryNotify(func() error {
+			tableCreateOpts := tableToTableCreateOpts[table]
+			_, err := gorethink.DB(dbName).TableCreate(table, tableCreateOpts...).RunWrite(session)
 			return err
-		}
+		}, config, func(err error, d time.Duration) {
+			fmt.Printf("Error; retrying in %s: %#v\n", d, err)
```
Comment (jdoliner) [inline src/server/pfs/db/driver.go]: Last little tweak, this should log using `lion` instead of `fmt` to match the rest of our code base. Also it'd be good to describe where the error is coming from, ie `Error creating table`. Also using `%s` and `err.Error()` instead of `%#v` might be a good idea but those might also be equivalent. I'm not quite sure.

Comment (sjezewski) [inline src/server/pfs/db/driver.go]: Good point. Added lion support.

Seems like they're all equivalent:

https://play.golang.org/p/zDsEx-cTLr

So I just went with `%v` (since that's my goto)

**Comment by jdoliner** [comment]
1epkgz
