### PR TITLE
Fix #471 and #475

### LINKED ISSUE #471: Sometimes Job's state stays at "running" even when it has failed

### PR DESCRIPTION
**Pull request by derekchiang**
@jdoliner

### CODE REVIEW

File: src/server/cmd/job-shim/main.go [hunk 1]
```diff
@@ -47,6 +47,23 @@ func do(appEnvObj interface{}) error {
 				os.Exit(0)
 			}
 
+			// Make sure that we call FinishJob even if something caused a panic
+			defer func() {
+				if r := recover(); r != nil {
+					if _, err := ppsClient.FinishJob(
```
Comment (jdoliner) [inline src/server/cmd/job-shim/main.go]: This seems unlikely but could we bulletproof this against calling `FinishJob` below, then getting a panic recovering and calling FinishJob again? That could be a nasty bug since the job would finish while one of the pods is still running.

Comment (jdoliner) [inline src/server/cmd/job-shim/main.go]: In general I think it's good to defend against things like this even when it seems hard for the current code to exhibit the bug. Someone could easily come along and add some buggy code after the call the `FinishJob` and wind up with an incredibly confusing error to debug.

But also I disagree that there isn't room for panicing because we `defer` another function on line `85` to unmount the volume. If that function panics then we'll hit this bug. So all it really takes is someone making a mistake in `Unmount` and we'll hit this issue.

I think it's worth an extra boolean variable to defend against that case.

Also could we add a log statement when we recover so we know that it's a bug in the job-shim that caused the failure rather than an actually failure? I think that'd help with debugging too.

**Comment by jdoliner** [comment]
[LGTM](http://lgtm.in/i/oylAS6FJn)

**Comment by derekchiang** [comment]
epic
