### PR TITLE
Rapid pipeline updates

### LINKED ISSUE #3045: Jobs get wedged after a updating a pipeline with `--reprocess` multiple times in quick succession.
**What happened?**:
Jobs get wedged after a updating a pipeline with `--reprocess` multiple times in quick succession.

Digging in a bit, I see this in the raw logs:
```{"pipelineName":"<pipeline name>","workerId":"pipeline-<name>-v10-lpzzg","ts":"2018-07-12T13:52:00.086231497Z","message":"worker: watch closed or error running the worker process: job's version (8) doesn't match pipeline's version (10), this should automatically resolve when the worker is updated; retrying in 13.502824341s"}```

`kubectl get pods` shows v10 is running:
```
pipeline-<name>-v10-4bdcb                             2/2       Running   0          23m
pipeline-<name>-v10-4bmks                             2/2       Running   0          23m
pipeline-<name>-v10-55dx5                             2/2       Running   0          23m
...
```

`pachctl list-jobs -p <name>` shows 2 jobs that think they are running (note first and last lines):
```
2500e8912a1d483eb3e3e69e4abfb00e <name>/a4e0b23d454440158c4d01a3da4f9100 26 minutes ago -             0       0 + 0 / 158063         0B       0B       running
3464159fd57c417b94a1a58474462693 <name>/95f8a5b10ba248d8b7e0ee383b0acdc2 18 hours ago   23 minutes    0       563 + 156148 / 151412  49.14KiB 155.5MiB success
735b8f41ee334c86963dacfe3c4d4ffb <name>/b28b9de29b1d4683913c7cd558806554 19 hours ago   34 minutes    0       0 + 150886 / 150886    0B       0B       success
c93063b08a60434dac46388f4b6a9da9 <name>/89293db918994242ab05bda827930818 19 hours ago   30 minutes    0       1056 + 154354 / 150886 120.8KiB 393.5MiB success
...
6ef11c3f7efe494db6fc1ee7de1e5222 <name>/4220777b3f7d4d6e96b8d698a68f2d85 38 hours ago   45 minutes    0       2 + 141708 / 141710    168B     134.9KiB success
a61dc215e6bd45c2ad08101e63a38d17 <name>/23f1356683594d79a239daf4c7b97116 38 hours ago   40 minutes    1       276 + 145682 / 141710  22.85KiB 59.71MiB success
18d84336e8ac414fac1b692fe43a09fd <name>/c99b497e825b448fac57d713eafa709a 39 hours ago   About an hour 0       0 + 143557 / 141436    0B       0B       running
```

After running `pachctl delete-job 18d84336e8ac414fac1b692fe43a09fd`, everything unwedges and job `2500e8912a1d483eb3e3e69e4abfb00e` starts moving.

**What you expected to happen?**:
The new job to run immediately

**How to reproduce it (as minimally and precisely as possible)?**:

I believe this happens when I run `pachctl update-pipeline` with `--reprocess` and a new image version more than once in quick succession. I haven't tried to explicitly reproduce, but have hit this several times over the past few days.

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
-- 21:31 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```

-- 21:31 $ pachctl version
COMPONENT           VERSION
pachctl             1.7.4
pachd               1.7.4
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GKE

### LINKED ISSUE #3046: Cron input is triggering twice every period
**What happened?**:
I have a job running on a cross of an hourly cron and a manually updated input repo. I see 2 commits to the cron repo every hour, very close to each other.

Here is the pipeline spec:
```
{
  "pipeline": {
    "name": "<name>"
  },
  "transform": {
    "image": "{IMAGE}",
    "cmd": ["{CMD}"]
  },
  "input": {
    "cross": [
    {
      "cron": {
        "name": "trigger",
        "spec": "@hourly",
        "repo": "hourly_trigger"
      }
    }, {
      "atom": {
        "repo": "<other input>",
        "glob": "/*"
      }
    }]
  },
  "enable_stats": true,
  "parallelism_spec": {
    "constant": 1
  }
}
```

Here are recent commits to the `hourly_trigger` repo:
```
-- 21:31 $ pachctl list-commit hourly_trigger -n 10
REPO           ID                               PARENT                           STARTED        DURATION           SIZE
hourly_trigger 207e1126a8304331aa3e092fdb63bc80 e6cbe84563f542a4adddb66481ee04c8 33 minutes ago 1 second           26B
hourly_trigger e6cbe84563f542a4adddb66481ee04c8 b2fecc3dea014c2d8e9792566033a183 33 minutes ago Less than a second 26B
hourly_trigger b2fecc3dea014c2d8e9792566033a183 b4261e57420a44d7980477cf14b5996a 2 hours ago    2 seconds          26B
hourly_trigger b4261e57420a44d7980477cf14b5996a 7f31df3af7ca4f7ebce1c865fcb3c52c 2 hours ago    Less than a second 26B
hourly_trigger 7f31df3af7ca4f7ebce1c865fcb3c52c 9fcded16b1944252b0609b1d0f5b20d6 3 hours ago    2 seconds          26B
hourly_trigger 9fcded16b1944252b0609b1d0f5b20d6 ed3659b44a0e4830934dc9e7f953065e 3 hours ago    Less than a second 26B
hourly_trigger ed3659b44a0e4830934dc9e7f953065e 46b1d47047a24af98c8914a02f71e069 4 hours ago    1 second           26B
hourly_trigger 46b1d47047a24af98c8914a02f71e069 d6cf61aecb9b4275912ef4091e5542dc 4 hours ago    Less than a second 26B
hourly_trigger d6cf61aecb9b4275912ef4091e5542dc 8e97abee9d4d443cb6537674c3830e81 5 hours ago    1 second           26B
hourly_trigger 8e97abee9d4d443cb6537674c3830e81 f9597d6016814bafbc8227e22b54e7ab 5 hours ago    Less than a second 26B
```

Here is the raw inspect-commit of 2 commits that happened close to each other:
```
-- 21:31 $ pachctl inspect-commit hourly_trigger 207e1126a8304331aa3e092fdb63bc80 --raw
{
  "commit": {
    "repo": {
      "name": "hourly_trigger"
    },
    "id": "207e1126a8304331aa3e092fdb63bc80"
  },
  "parentCommit": {
    "repo": {
      "name": "hourly_trigger"
    },
    "id": "e6cbe84563f542a4adddb66481ee04c8"
  },
  "started": "2018-07-11T15:00:00.355139592Z",
  "finished": "2018-07-11T15:00:02.338848560Z",
  "sizeBytes": "26",
  "subvenance": [<redacted>]
  "tree": {
    "hash": "e8a305e68c6dceeacaaa3957e78d28c6d13bb7d9d249c7cd32a438df522cfb209109413fc8a179ca6ad7e454df37ee7a15772e516e5a0a9c91f0e609edf64e8e"
  }
}
-- 21:31 $ pachctl inspect-commit hourly_trigger e6cbe84563f542a4adddb66481ee04c8 --raw
{
  "commit": {
    "repo": {
      "name": "hourly_trigger"
    },
    "id": "e6cbe84563f542a4adddb66481ee04c8"
  },
  "parentCommit": {
    "repo": {
      "name": "hourly_trigger"
    },
    "id": "b2fecc3dea014c2d8e9792566033a183"
  },
  "childCommits": [
    {
      "repo": {
        "name": "hourly_trigger"
      },
      "id": "207e1126a8304331aa3e092fdb63bc80"
    }
  ],
  "started": "2018-07-11T15:00:00.360974638Z",
  "finished": "2018-07-11T15:00:00.723664161Z",
  "sizeBytes": "26",
  "subvenance": [<redacted>],
  "tree": {
    "hash": "e8a305e68c6dceeacaaa3957e78d28c6d13bb7d9d249c7cd32a438df522cfb209109413fc8a179ca6ad7e454df37ee7a15772e516e5a0a9c91f0e609edf64e8e"
  }
```

The other, manually updated repo has not changed:
```
REPO            ID                               PARENT                           STARTED      DURATION           SIZE
<input> c49c931842ee4415b66ed2c09e7b6472 4a5ad9bb42a64eacb8078753108cea75 24 hours ago Less than a second 218B
<input> 4a5ad9bb42a64eacb8078753108cea75 457519af0b29413694d492fde1f9babf 24 hours ago Less than a second 196B
<input> 457519af0b29413694d492fde1f9babf 996962d9424742cc8571317c5d5cd149 24 hours ago Less than a second 170B
<input> 996962d9424742cc8571317c5d5cd149 f3cd2a184b4443e88e6c5704e588cfbe 24 hours ago Less than a second 135B
<input> f3cd2a184b4443e88e6c5704e588cfbe a485281250e34267b7f1d66a1d6b1871 24 hours ago Less than a second 135B
<input> a485281250e34267b7f1d66a1d6b1871 af8528d10c414f9cafef1eab4d0db438 24 hours ago Less than a second 135B
<input> af8528d10c414f9cafef1eab4d0db438 a5e5a3d0e21e4766833677b6de2db084 24 hours ago Less than a second 135B
<input> a5e5a3d0e21e4766833677b6de2db084 96a9d3b9d649406e868593eb6f74ed46 24 hours ago Less than a second 135B
<input> 96a9d3b9d649406e868593eb6f74ed46 792e95f4c9a94d2281b0fcf51b8ae3b3 24 hours ago Less than a second 135B
<input> 792e95f4c9a94d2281b0fcf51b8ae3b3 cbd459ddadf649da8971197e33bec324 24 hours ago Less than a second 135B
```

This started happening well after the cron repo was created. It seemed to correlate with a number of very quick commits to the other repo in the cross, but I can't confirm that. I have not tried to reproduce from scratch.

**What you expected to happen?**:
Hourly cron to trigger once per hour.

**How to reproduce it (as minimally and precisely as possible)?**:
I have not tried to reproduce from scratch.

**Anything else we need to know?**:
I have one pachd pod.

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
-- 21:31 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.2", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}```

- Pachyderm CLI version (use `pachctl version`):
```
-- 21:31 $ pachctl version
COMPONENT           VERSION
pachctl             1.7.4
pachd               1.7.4
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): GKE

### PR DESCRIPTION
**Pull request by jdoliner**
Fixes #3045 
Fixes #3046

### CODE REVIEW

File: src/server/pps/server/master.go [hunk 1]
```diff
@@ -238,6 +238,10 @@ func (a *apiServer) master() {
 			}
 		}
 	}, backoff.NewInfiniteBackOff(), func(err error, d time.Duration) error {
+		for _, c := range a.monitorCancels {
+			c()
+		}
+		a.monitorCancels = make(map[string]func())
```
Comment (msteffen) [inline src/server/pps/server/master.go]: This PR might just not be ready yet, but does this map get added to anywhere?

Comment (jdoliner) [reply src/server/pps/server/master.go]: It does, you're not going to see it in the diff though because the code was already there and hasn't changed. The main change here is that we're cancelling all the monitor goros, and clearing the map when the master process goes into backoff. This is because during this time we're not master so we shouldn't be doing master things such as making `cron` commits.

File: src/server/worker/api_server.go [hunk 2]
```diff
@@ -1228,10 +1228,13 @@ func (a *APIServer) worker() {
 				}
 				return fmt.Errorf("error from InspectJob(%v): %+v", jobID, err)
 			}
-			if jobInfo.PipelineVersion != a.pipelineInfo.Version {
-				return fmt.Errorf("job's version (%d) doesn't match pipeline's "+
+			if jobInfo.PipelineVersion < a.pipelineInfo.Version {
+				continue
+			}
+			if jobInfo.PipelineVersion > a.pipelineInfo.Version {
+				return fmt.Errorf("job %s's version (%d) greater than pipeline's "+
```
Comment (jdoliner) [inline src/server/worker/api_server.go]: This is the other major bug fix. The issue here was that if you wind up with a job whose `PipelineVersion` is lower than the worker's current version then it'll go into backoff, expecting that the worker will be recreated soon and have the correct version. This works when the `PipelineVersion` is higher, but when it's lower we want to just skip the job.
