### PR TITLE
Native JupyterHub deployments

### LINKED ISSUE #4737: `pachctl deploy storage` doesn't respect pachyderm contexts
`pachctl deploy storage` uses the active kubernetes context, rather than pachyderm context. Because of this, unexpected behavior can occur if the current kubernetes context and active pachyderm context do not point to the same cluster.

### PR DESCRIPTION
**Pull request by ysimonson**
Adds support for deploying jupyterhub-pachyderm via `pachctl`, rather than using the python script.

Deployments can be done via `pachctl deploy jupyterhub`. It is a separate command from `pachctl deploy` because some intermediate steps must be done between standing up a pachyderm cluster and deploying jupyterhub-pachyderm (enterprise+auth must be enabled, user must login.)

Jupyterhub-pachyderm can be undeployed via `pachctl undeploy --jupyterhub`.

A few changes to deployments had to be made in the process, and it uncovered a couple of bugs that were resolved:
* Secret deployment and undeploy now use pachyderm contexts, rather than hoping the kubectl context points to the same cluster. This is a little gnarly because they still call into kubectl rather than using the API; they generate a kube config on-the-fly with the pachyderm context patched on top of the base config.
* `pachctl deploy` subcommands now only expose flags that they actually use.
* Better handling of pachyderm configs with no contexts.
* Especially with these changes, `pachctl undeploy`'s `--all` flag was too ambiguous. It has been deprecated, but not yet removed. It's successor is `--metadata`.
* `pachctl undeploy` now always removes the relevant pachyderm context(s).

A bunch of improvements were also made to the reset script:
* Deletes hostpath mounts to prevent the pachyderm cluster from getting in a bad state.
* No longer deploys dashboard by default; it can be enabled with `--dashboard`.
* Supports jupyterhub deployments via `--jupyterhub`.

Tested in the jupyterhub-pachyderm sister tickets:
- https://github.com/pachyderm/jupyterhub-pachyderm/pull/24
- https://github.com/pachyderm/jupyterhub-pachyderm/pull/37
- https://github.com/pachyderm/jupyterhub-pachyderm/pull/38

Closes #4737

### CODE REVIEW

File: src/server/pkg/deploy/cmds/cmds.go [hunk 1]
```diff
@@ -28,15 +35,89 @@ import (
...
+	tmpfile, err := ioutil.TempFile("", "transient-kube-config-*.yaml")
+	if err != nil {
+		return errors.Wrapf(err, "failed to create transient kube config")
+	}
+	defer os.Remove(tmpfile.Name())
+	tmpfile.Write([]byte(fmt.Sprintf(configTemplate, context.ClusterName, context.AuthInfo, context.Namespace)))
+	tmpfile.Close()
+
+	var environ []string = nil
+	if context != nil {
```
Comment (ysimonson) [inline src/server/pkg/deploy/cmds/cmds.go]: This generates a kube config on-the-fly with the pachyderm context built on top of the base config. This is an improvement over what we had before because, previously, we just assumed the kube and pachyderm contexts pointed to the same cluster. But it still seems pretty hackey.

Ideally, we'd use the kube API rather than calling kubectl for deployment/undeployment, but it became way too cumbersome to try to reproduce the same functionality that kubectl does here.

That said, I'd love to hear alternative suggestions that might clean this up - it's the part I'm most unhappy with in this PR.

File: go.mod [hunk 2]
```diff
@@ -106,37 +96,39 @@ require (
...
-	sigs.k8s.io/yaml v1.1.0 // indirect
+	rsc.io/letsencrypt v0.0.3 // indirect
+	sigs.k8s.io/yaml v1.1.0
 )
 
 // Holy shit, the docker library versions are a clusterfuck, see https://github.com/moby/moby/issues/39302
 // For the moment, the windows build requires a fix that has not been tagged with an official release
 replace github.com/docker/docker => github.com/docker/docker v1.4.2-0.20191213113251-3452f136aa68
+
+replace github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible
```
Comment (ysimonson) [inline go.mod:134]: This was needed because the helm library does this

File: src/server/pkg/deploy/cmds/cmds.go (hunk 1 above)
Comment (jdoliner) [reply src/server/pkg/deploy/cmds/cmds.go:69]: Yeah that's tricky, we actually used to send this stuff directly over the kube api, but we moved to call kubectl directly because it proved to be so hard to replicate the functionality of kubectl, particularl with respect to auth. You could conceivably make this a little nicer by using structs from the kubeapi rather than templates and then serializing them to yaml when you want to give them to kubectl... not 100% sure if that's going to be nicer though. That's probably what I would do, but I'm not sure my sense of how to make deployment to kube nice hasn't always yielded the best results.

Comment (ysimonson) [reply src/server/pkg/deploy/cmds/cmds.go:59]: Yeah using the proper kube objects makes sense, done
