### PR TITLE
Fixes hanging jobs when glob pattern is non-existant static file.

### LINKED ISSUE #3068: glob pattern for a static file that doesn't exist
**What happened?**:
job goes into infinite restart loop stuck in "starting"
```
56cd7af30335445d948238587d1124c7 suneeta/4232b4d9520e437a83168c0b0337ebcf 5 minutes ago  -                  29      0 + 0 / 0 0B       0B   starting
```

**What you expected to happen?**:
User code should run but have zero datums

**How to reproduce it (as minimally and precisely as possible)?**:

Create a pipeline with a glob pattern for a file that doesn't actually match anything. 

Example:
        "atom": {
          "glob": "/non_existent_image.jpg",
          "repo": "repo1"
        }
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 1.7.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

### PR DESCRIPTION
**Pull request by kevindelgado**
Fixes #3068 
Escapes `PathNotFound` db lookup errors so that a non-existent glob pattern still enables successful jobs ran over 0 datum. Adds server tests for non-existent glob patterns. Tested locally (docker for desktop) with pipeline spec containing non-existent static glob pattern.

### CODE REVIEW

File: src/server/pfs/server/server_test.go [hunk 1]
```diff
@@ -2984,6 +2984,14 @@ func TestGlob(t *testing.T) {
 	fileInfos, err = c.GlobFile(repo, "master", "dir1/*")
 	require.NoError(t, err)
 	require.Equal(t, numFiles, len(fileInfos))
+	fileInfos, err = c.GlobFile(repo, "master", "/non-existant-glob*")
+	require.NoError(t, err)
+	require.Equal(t, 0, len(fileInfos))
+	fileInfos, err = c.GlobFile(repo, "master", "/non-existant-static-file")
+	require.NoError(t, err)
+	require.Equal(t, 0, len(fileInfos))
+	fmt.Println("end custom tests")
```
Comment (brycemcanally) [inline src/server/pfs/server/server_test.go]: This should probably be removed.

File: src/server/pfs/server/server_test.go [hunk 2]
```diff
@@ -2984,6 +2984,14 @@ func TestGlob(t *testing.T) {
 	fileInfos, err = c.GlobFile(repo, "master", "dir1/*")
 	require.NoError(t, err)
 	require.Equal(t, numFiles, len(fileInfos))
+	fileInfos, err = c.GlobFile(repo, "master", "/non-existant-glob*")
```
Comment (brycemcanally) [inline src/server/pfs/server/server_test.go]: Existent not existant. Minor nit pick lol.

File: src/server/pfs/server/server_test.go [hunk 3]
```diff
@@ -2984,6 +2984,14 @@ func TestGlob(t *testing.T) {
...
+	require.NoError(t, err)
+	require.Equal(t, 0, len(fileInfos))
+	fileInfos, err = c.GlobFile(repo, "master", "/non-existant-static-file")
```
Comment (brycemcanally) [inline src/server/pfs/server/server_test.go]: Same as above.

File: src/server/pkg/hashtree/db.go [hunk 4]
```diff
@@ -265,6 +265,10 @@ func List(rs []io.ReadCloser, pattern string, f func(string, *NodeProto) error)
 func glob(tx *bolt.Tx, pattern string, f func(string, *NodeProto) error) error {
 	if !IsGlob(pattern) {
 		node, err := get(tx, pattern)
+		if Code(err) == PathNotFound {
+			// glob pattern is for a static file that doesn't exist, no match
```
Comment (brycemcanally) [inline src/server/pkg/hashtree/db.go]: I don't think it really makes sense to call a file in pfs static vs non-static because there is no notion of a non-static file in pfs.

File: src/server/pfs/server/server_test.go (hunk 3 above)
Comment (brycemcanally) [reply src/server/pfs/server/server_test.go]: Also, the static file stuff mentioned below.

File: src/server/pfs/server/server_test.go (hunk 1 above)
Comment (kevindelgado) [reply src/server/pfs/server/server_test.go]: Done.

File: src/server/pfs/server/server_test.go (hunk 2 above)
Comment (kevindelgado) [reply src/server/pfs/server/server_test.go]: Done.

File: src/server/pfs/server/server_test.go (hunk 3 above)
Comment (kevindelgado) [reply src/server/pfs/server/server_test.go]: Done.

File: src/server/pkg/hashtree/db.go (hunk 4 above)
Comment (kevindelgado) [reply src/server/pkg/hashtree/db.go]: Done.

File: src/server/pkg/hashtree/db.go [hunk 5]
```diff
@@ -265,6 +265,10 @@ func List(rs []io.ReadCloser, pattern string, f func(string, *NodeProto) error)
 func glob(tx *bolt.Tx, pattern string, f func(string, *NodeProto) error) error {
 	if !IsGlob(pattern) {
 		node, err := get(tx, pattern)
+		//if Code(err) == PathNotFound {
```
[the remark this answers is not in the document]
Comment (kevindelgado) [reply src/server/pkg/hashtree/db.go]: ya sorry, was just trying to trigger the ci.
