### PR TITLE
Fix a bug where pachd servers can cut off contact with workers and not re-establish contact

### LINKED ISSUE #1660: Problem with re-discovering workers results in stuck job
Looking at the logs from a production cluster, I see the following three log lines in the following order:

```
2017-04-12T16:51:47Z INFO  watching `pachyderm_pps/workers/pipeline-XXX-v1/` for workers
2017-04-12T16:51:47Z ERROR error discovering workers: watcher for prefix pachyderm_pps/workers/pipeline-XXX-v1/ closed for unknown reasons; retrying in 305.523625ms
2017-04-12T17:09:56Z INFO  launching job manager for job c2aaaaef-9fff-4f71-9549-e72d392e4dd9
```

Here, the job `c2aaaaef-9fff-4f71-9549-e72d392e4dd9` is the job that got stuck.  `XXX` is the pipeline that produced the job.  From the log, it's clear that for whatever reason the `Watch` for discovering workers closed.  Then, for some reason pachd was unable to re-create a `Watch`.  Thus, the job was getting stuck because it didn't have any available workers to talk to.

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #1660 

The issue is that, currently the lifetime of a worker pool is tied to the lifetime of the process that created it.  So when you have a multi-node cluster, you might end up in a situation where a job created a worker pool, then another job starts using the worker pool, then the first job exits, bringing the worker pool down with it.  Thus the second job is stuck because it doesn't have workers to use anymore.

### CODE REVIEW

File: src/server/cmd/worker/main.go [hunk 1]
```diff
@@ -174,7 +174,11 @@ func do(appEnvObj interface{}) error {
 	if err != nil {
 		return err
 	}
-	etcdClient.KeepAlive(context.Background(), resp.ID) // keepalive forever
+
+	// keepalive forever
+	if _, err := etcdClient.KeepAlive(context.Background(), resp.ID); err != nil {
+		return err
+	}
```
Comment (jdoliner) [inline src/server/cmd/worker/main.go]: Hardest lyfe

**Comment by jdoliner** [comment]
This looks good to me, although I don't feel totally confident that I've understood all the concurrency logic in worker_pool. But that was true before this pr.
