### PR TITLE
Maintain crashing monitor in CRASHING state.

### LINKED ISSUE #6513: Pipelines don't seem to transition out of CRASHING
I submitted a pipeline that requires 8 CPUs (in its `resource_requests` section, it's just the opencv "montage" example that I'm using to test autoscaling), causing GKE to autoscale the cluster to add a node that such a pod would fit on.  This all worked fine, and the job ran, and the results are correct.  However, pachd keeps the pod in the crashing state.  Here's a subset of the logs from pachd:

```
$ kubectl logs pachd-6768f57655-9lswh | grep CRASH
2021-07-10T23:03:55Z INFO SetPipelineState attempting to move "edges" from one of {PIPELINE_RUNNING,PIPELINE_CRASHING} to PIPELINE_STANDBY
2021-07-10T23:04:14Z INFO SetPipelineState attempting to move "edges" from one of {PIPELINE_RUNNING,PIPELINE_CRASHING} to PIPELINE_STANDBY
2021-07-10T23:04:21Z INFO SetPipelineState attempting to move "montage" to PIPELINE_CRASHING (reason: "0/1 nodes are available: 1 Insufficient cpu.")
2021-07-10T23:04:21Z INFO SetPipelineState moving pipeline montage from PIPELINE_RUNNING to PIPELINE_CRASHING
2021-07-10T23:05:11Z INFO SetPipelineState attempting to move "montage" to PIPELINE_CRASHING (reason: "0/2 nodes are available: 1 Insufficient cpu, 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.")
2021-07-10T23:05:11Z INFO SetPipelineState moving pipeline montage from PIPELINE_CRASHING to PIPELINE_CRASHING
2021-07-10T23:06:56Z INFO SetPipelineState attempting to move "edges" from one of {PIPELINE_RUNNING,PIPELINE_CRASHING} to PIPELINE_STANDBY
```

Here's a timeline on the Kubernetes level:

```
Events:
  Type     Reason            Age                From                Message
  ----     ------            ----               ----                -------
  Warning  FailedScheduling  11m                default-scheduler   0/1 nodes are available: 1 Insufficient cpu.
  Normal   TriggeredScaleUp  11m                cluster-autoscaler  pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/hub-kkslhhehpxxm/zones/us-central1-c/instanceGroups/gke-hub-c0-mkakb4v5bq-n1-standard-16-5b84cdff-grp 0->1 (max: 4)}]
  Warning  FailedScheduling  10m (x3 over 10m)  default-scheduler   0/2 nodes are available: 1 Insufficient cpu, 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Normal   Scheduled         10m                default-scheduler   Successfully assigned default/pipeline-montage-v1-gjvh4 to gke-hub-c0-mkakb4v5bq-n1-standard-16-5b84cdff-sjr4
  Normal   Pulling           9m57s              kubelet             Pulling image "pachyderm/worker:2.0.0-beta.1"
  Normal   Pulled            8m58s              kubelet             Successfully pulled image "pachyderm/worker:2.0.0-beta.1"
  Normal   Created           8m57s              kubelet             Created container init
  Normal   Started           8m57s              kubelet             Started container init
  Normal   Pulling           8m57s              kubelet             Pulling image "dpokidov/imagemagick:7.0.10-58"
  Normal   Pulled            8m41s              kubelet             Successfully pulled image "dpokidov/imagemagick:7.0.10-58"
  Normal   Created           8m40s              kubelet             Created container user
  Normal   Started           8m40s              kubelet             Started container user
  Normal   Pulling           8m40s              kubelet             Pulling image "pachyderm/pachd:2.0.0-beta.1"
  Normal   Pulled            8m38s              kubelet             Successfully pulled image "pachyderm/pachd:2.0.0-beta.1"
  Normal   Created           8m38s              kubelet             Created container storage
  Normal   Started           8m38s              kubelet             Started container storage
```

So yes, the pipeline was CRASHING for about a minute, but it started up and ran to completion.  So I think pachd should remove the CRASHING tag in that case.

The underlying rc seems to be in a good state:

```
$ kubectl jq rc pipeline-montage-v1 .status
{
    "availableReplicas": 1,
    "fullyLabeledReplicas": 1,
    "observedGeneration": 2,
    "readyReplicas": 1,
    "replicas": 1
}
```

(Though I wonder if observedGeneration confuses pachd in some way?)

There might be some sort of loop we enter on error that we don't recover from:

```
$ kubectl logs pachd-6768f57655-9lswh | grep montage | grep PPS
2021-07-10T23:04:19Z INFO PPS master: processing event for "montage"
2021-07-10T23:04:20Z ERROR PPS master: error retrieving RC for "montage": RC not found; retrying in 585.914553ms
2021-07-10T23:04:20Z ERROR PPS master: error retrieving RC for "montage": RC not found; retrying in 675.141217ms
2021-07-10T23:04:21Z INFO PPS master: creating resources for pipeline "montage"
2021-07-10T23:04:21Z INFO PPS master: upserting workers for "montage"
2021-07-10T23:04:21Z INFO PPS master: processing event for "montage"
2021-07-10T23:04:21Z INFO PPS master: scaling up workers for "montage"
2021-07-10T23:04:21Z INFO PPS master: monitoring pipeline "montage"
2021-07-10T23:04:21Z INFO PPS master: processing event for "montage"
2021-07-10T23:04:21Z INFO PPS master: scaling up workers for "montage"
2021-07-10T23:04:21Z ERROR PPS master: error scaling up: error updating RC: Operation cannot be fulfilled on replicationcontrollers "pipeline-montage-v1": the object has been modified; please apply your changes to the latest version and try again
2021-07-10T23:04:21Z ERROR PPS master: error updating resources for pipeline "montage": error updating RC: Operation cannot be fulfilled on replicationcontrollers "pipeline-montage-v1": the object has been modified; please apply your changes to the latest version and try again; retry
ing in 506.543753ms
2021-07-10T23:04:22Z INFO PPS master: processing event for "montage"
2021-07-10T23:04:22Z INFO PPS master: scaling up workers for "montage"
2021-07-10T23:04:22Z INFO PPS master: processing event for "montage"
2021-07-10T23:04:22Z INFO PPS master: scaling up workers for "montage"
2021-07-10T23:04:23Z INFO PPS master: processing event for "montage"
2021-07-10T23:04:23Z INFO PPS master: scaling up workers for "montage"
2021-07-10T23:04:27Z INFO PPS master: processing event for "montage"
```

The scaling up / processing sequence continues indefinitely, every 4 seconds or so.

### PR DESCRIPTION
**Pull request by PFedak**
Fixes #6513 
Need to figure out a way to test this, would have to delay a pod's startup/make it stop crashing without updating the pipeline.

### CODE REVIEW

File: src/server/pps/cmds/cmds_test.go [hunk 1]
```diff
@@ -739,3 +740,53 @@ func TestNoWarningTagSpecified(t *testing.T) {
...
+
+	require.NoErrorWithinT(t, 10*time.Second, func() error {
+		return tu.BashCmd(`
+		pachctl list pipeline \
+		| match 'name: my-pipeline' \
+		| match 'crashing'
+		`).Run()
+	})
+
+	// prevent new pods from being scheduled
```
Comment (jrockway) [inline src/server/pps/cmds/cmds_test.go:780]: // allow new pods to be scheduled

**Review by jrockway — APPROVED** [review]
Looks good.  (The key insight is that the first line of startPipelineMonitor is stopCrashingPipelineMonitor.)
