### PR TITLE
Fix worker metrics in 2.x

### LINKED ISSUE #6809: Updated Prometheus port name in pachd but not pipelines
**What happened?**:
service monitor set to connect to `prom-metrics` port which is what pachd exposes but no pipelines are watched.
**What you expected to happen?**:
all pipelines watched too
**How to reproduce it (as minimally and precisely as possible)?**:
deploy a pipeline. they still deploy with the prometheus port named `prometheus-metrics` instead of `prom-metrics`
**Anything else we need to know?**:
https://github.com/pachyderm/pachyderm/blob/master/src/internal/deploy/assets/assets.go#L740

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- If you deployed with helm, the values you used (`helm get values pachyderm`):
- OS (e.g. from /etc/os-release):
- Others:

[AB#128](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/128)

### PR DESCRIPTION
**Pull request by Tryneus**
Metrics were broken in a couple ways - the identifier for the service port was incorrect due to an incomplete identifier change, and workers were not actually incrementing any of the metric counters.  Fixed by incrementing counters in `datum.go`.  Also changed the worker metrics to use `promauto` to remove a little boilerplate.

Fixed #6809 and #6811

### CODE REVIEW

File: src/server/worker/datum/datum.go [hunk 1]
```diff
@@ -26,6 +26,7 @@ import (
 	"github.com/pachyderm/pachyderm/v2/src/pps"
 	pfsserver "github.com/pachyderm/pachyderm/v2/src/server/pfs"
 	"github.com/pachyderm/pachyderm/v2/src/server/worker/common"
+	workerStats "github.com/pachyderm/pachyderm/v2/src/server/worker/stats"
```
Comment (PFedak) [inline src/server/worker/datum/datum.go:29]: was this just for clarity, or is there another `stats`?

File: src/server/worker/datum/datum.go [hunk 2]
```diff
@@ -161,6 +162,11 @@ func (s *Set) WithDatum(meta *Meta, cb func(*Datum) error, opts ...Option) error
 				if retErr == nil || i == d.numRetries {
 					retErr = d.finish(retErr)
 				}
+				duration := time.Duration(int64(d.meta.Stats.ProcessTime.GetNanos()) + d.meta.Stats.ProcessTime.GetSeconds()*1000000000)
```
Comment (PFedak) [inline src/server/worker/datum/datum.go:165]: maybe use `time.Second` to avoid the zeros
```suggestion
				duration := time.Duration(d.meta.Stats.ProcessTime.GetNanos()) + time.Duration(d.meta.Stats.ProcessTime.GetSeconds())*time.Second
```

**Review by PFedak — APPROVED** [review]
LGTM, just one readability change

File: src/server/worker/datum/datum.go (hunk 1 above)
Comment (Tryneus) [reply src/server/worker/datum/datum.go:29]: It's not a direct naming conflict, but there are stats on the datum object that I didn't want this to be confused with.

File: src/server/worker/datum/datum.go (hunk 2 above)
Comment (Tryneus) [reply src/server/worker/datum/datum.go]: good point, thanks!

**Comment by tybritten** [comment]
can we get this pulled into the next RC?

**Comment by Tryneus** [comment]
@tybritten - this has been cherry-picked into `2.0.x`, it should be in the next RC
