### PR TITLE
Handle stats with no input datums

### LINKED ISSUE #3337: If a job has no input datums, but does have stats enabled, the job's stats commit is never closed
Corner case encountered during testing (and I actually found two closely-related issues), but I ran into this while working on migration and didn't have time to fix it. The relevant code is in `worker/master.go`:
```
// Handle the case when there are no datums
if df.Len() == 0 {
	if err := a.updateJobState(ctx, jobInfo, nil, pps.JobState_JOB_SUCCESS, ""); err != nil {
		return err
	}
	_, err := pachClient.PfsAPIClient.FinishCommit(ctx, &pfs.FinishCommitRequest{
		Commit: jobInfo.OutputCommit,
		Empty:  true,  // indicates a failed job (downstream jobs will be 'failed' instead of 'success/no datums')
	})
	// also, no stats tree handling
	return err
}
```

### PR DESCRIPTION
**Pull request by ysimonson**
Fixes #3337.

I'm not familiar with stats commits, so this change is basically a guess. If you're looking for something more thorough or different, let me know!

### CODE REVIEW

File: src/server/worker/stats_test.go [hunk 1]
```diff
@@ -249,3 +250,66 @@ func TestPrometheusStats(t *testing.T) {
...
 	}
 }
+
+// Regression: stats commits would not close when there were no input datums.
+//For more info, see github.com/pachyderm/pachyderm/issues/3337
+func TestCloseStatsCommitWithNoInputDatums(t *testing.T) {
+	c := getPachClient(t)
+	defer require.NoError(t, c.DeleteAll())
+
+	// TODO(ys): is this necessary?
```
Comment (msteffen) [inline src/server/worker/stats_test.go]: I'm actually not 100% sure either (I'll have to check), but I think it might be, and that would explain why we have so few stats tests. If so, we should probably put this stuff in its own testing harness someday (not in this PR :-))

File: src/server/worker/stats_test.go [hunk 2]
```diff
@@ -249,3 +250,66 @@ func TestPrometheusStats(t *testing.T) {
...
+	commitIter, err := c.FlushCommit([]*pfs.Commit{commit}, nil)
+	require.NoError(t, err)
+	
+	for {
+		_, err := commitIter.Next()
+		if err == io.EOF {
+			break
+		}
+		require.NoError(t, err)
+	}
```
Comment (msteffen) [inline src/server/worker/stats_test.go]: I know that this isn't fixed in this PR, but IMO we should add a TODO to check that the job succeeded (once we fix the known bug that currently makes that not happen)

File: src/server/worker/stats_test.go (hunk 1 above)
Comment (ysimonson) [reply src/server/worker/stats_test.go]: This is outdated, I checked and it is necessary

File: src/server/worker/stats_test.go (hunk 2 above)
Comment (ysimonson) [reply src/server/worker/stats_test.go]: Added the check
