### PR TITLE
Fix 415

### LINKED ISSUE #415: clients throw error when the S3 rate limit is hit
```
rpc error: code = 13 desc = invalid header field value "SlowDown: Please reduce your request rate.\n\tstatus code: 503, request id: 1134F6E552866794"
```
S3 has a request rate limit of `300 req/s` when that gets hit it triggers an rpc error in the golang client

### PR DESCRIPTION
**Pull request by derekchiang**
@jdoliner review?

The article that talks about S3 request rates: http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

Another thing that might be worth doing, assuming that this does not fix #415, would be to add a throttler so that we increase our request rates gradually, although it's unclear what "gradual" means from the article.

### CODE REVIEW

File: src/server/pkg/obj/obj.go [hunk 1]
```diff
@@ -66,7 +76,13 @@ func (b *BackoffReadCloser) Read(data []byte) (int, error) {
...
 		}
 		return nil
-	}, b.backoffConfig)
+	}, b.backoffConfig, func(err error, d time.Duration) {
+		protolion.Debugf("%v", RetryError{
+			err:               err,
+			timeTillNextRetry: d,
+			bytesProcessed:    bytesRead,
+		})
+	})
```
Comment (jdoliner) [inline src/server/pkg/obj/obj.go]: You should test this but I think by doing `Debugf` here you'll make it so these don't show up when users run the code since the debug level is set at `Info`. `Infof` will show up though.

**Comment by jdoliner** [comment]
LGTM
