### PR TITLE
Fix 3203 premature jobs

### LINKED ISSUE #3203: Job triggers prematurely from new __spec__ commit
**What happened?**:
Doing opencv demo, I called `update-pipeline -f edges.json` and 2 montage jobs triggered instead of 1. 

**What you expected to happen?**:
I expected a new edges job to trigger and THEN and montage job. Instead, I got a montage job immediately, followed by the expected edges & montage jobs. This was without reprocess flag, but not sure if that's relevant.

```
joeyzwicker$ pc update-pipeline -f ~/pachyderm/doc/examples/opencv/edges.json
joeyzwicker$ pc list-job
ID                               OUTPUT COMMIT                            STARTED           DURATION   RESTART PROGRESS     DL       UL       STATE
3ee2348f1ae74a91a6b68d80d01b882c montage/5305d3ea9a3547b5a454a9b80eb1e848 14 minutes ago    27 seconds 0       0 + 49 / 49  0B       0B       success
1ad0baf82ee94131902617b08f3d862e edges/cee9e4eb6ea84172a5198e1538da1ef3   14 minutes ago    25 seconds 0       0 + 7 / 7    0B       0B       success
ba81ea4ded254efa807d51a01ac90eb8 montage/c309fcaa6de54c1fb76e610239e5ff30 14 minutes ago    3 seconds  0       0 + 49 / 49  0B       0B       success
de8a5adb64dc46289c3b625e1fbcc359 montage/1026941690d44937a014807c4825876c 32 minutes ago    15 seconds 0       13 + 36 / 49 11.04MiB 5.501MiB success
7a2e21091abb401389117edbdf6c77a1 edges/95bc3eb0b72b439a96b625a5bf210ac5   32 minutes ago    4 seconds  0       1 + 1 / 2    1.583MiB 208.8KiB success
```

**How to reproduce it (as minimally and precisely as possible)?**:
Set up opencv demo, run it through normally once.
Then update-pipeline on edges.
You should get 3 jobs -- montage, then edges, then montage again. 

**Anything else we need to know?**:
Spoke to JD briefly. Current theory is that the montage pipeline is seeing the new commit on the edges `__spec__` repo and triggering a job instead of waiting for the edges job to run first and make an output commit. 

Weirdly, the "incorrect" montage job only has provenance on a single `__spec__` repo, when it should clearly have two. 

```
joeyzwicker$ pc inspect-commit montage c309fcaa6de54c1fb76e610239e5ff30
Commit: montage/c309fcaa6de54c1fb76e610239e5ff30
Parent: 243753f1954b4f99a10da02d2ddce8ae
Started: 19 minutes ago
Finished: 19 minutes ago
Size: 20.79MiB
Provenance:  __spec__/462c019981374b81b164b8c41bfa2788  edges/be9076ab2e93433793f6fa9be2f3deed  images/3597038a4a65481aae8fd45b2f169fe2
JosephZckersMBP:demo joeyzwicker$ pc inspect-commit montage 5305d3ea9a3547b5a454a9b80eb1e848
Commit: montage/5305d3ea9a3547b5a454a9b80eb1e848
Parent: c309fcaa6de54c1fb76e610239e5ff30
Started: 19 minutes ago
Finished: 19 minutes ago
Size: 20.79MiB
Provenance:  __spec__/7cc758a309684ddeabcc79e6b33c75c1  __spec__/462c019981374b81b164b8c41bfa2788  edges/cee9e4eb6ea84172a5198e1538da1ef3  images/3597038a4a65481aae8fd45b2f169fe2
```

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 1.7.10
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

### PR DESCRIPTION
**Pull request by kevindelgado**
This fixes #3203 by ensuring that the head is actually a subset of the commit provenance map rather than checking that the commit provenance map keyset is a subset of the branch head provenance (and creating erroneous commits when it is not).

### CODE REVIEW

**Comment by kevindelgado** [comment]
PTAL @msteffen

File: src/server/pachyderm_test.go [hunk 1]
```diff
@@ -1020,6 +1020,14 @@ func TestProvenance(t *testing.T) {
 	commitInfos, err = c.ListCommit(cPipeline, "master", "", 0)
 	require.NoError(t, err)
 	require.Equal(t, 2, len(commitInfos))
+
```
Comment (msteffen) [inline src/server/pachyderm_test.go]: Would it be possible to move this into its own test? I know TestProvenance is already pretty far gone, but in the past I've had bad experiences where we need to fix or remove complicated tests because we've changed our semantics, and we end up removing a bunch of auxiliary tests (like this one) that should still apply. If tests are smaller and more well-defined, then changing semantics without introducing regressions is easier

Comment (kevindelgado) [reply src/server/pachyderm_test.go]: Done.

**Comment by kevindelgado** [comment]
Comments addressed. PTAL @msteffen
