### PR TITLE
s3gateway improvements

### LINKED ISSUE #3892: Add timeout to s3gateway requests
Enforce request and response timeouts in s3gateway's HTTP requests

### LINKED ISSUE #3902: s3gateway: add support for versioning
Currently s3gateway does not support s3's object versioning. Add support for this, and tie it into pachyderm's versioning.

### LINKED ISSUE #3903: s3gateway: add support for multipart uploads
Currently s3gateway does not support s3's multipart uploads. Add support for this.

### LINKED ISSUE #3930: Cannot delete a file in the HEAD of a repo through an S3 gateway
**What happened?**:

Running `mc rm path-to-file` does not work.

I'm trying to test MinIO with Pachyderm. I was able to create and delete bucket by using the MinIO client. I was also able to upload a file to a Pachyderm repo.

```
    $ mc cp test.csv local/master.raw_data/test.csv
    test.csv:                  62 B / 62 B  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 206 B/s 0s
```

However, when I try to delete that file I get an error that it's not supported.
```
$ mc ls local/master.raw_data
    [2019-07-19 12:11:37 PDT]  2.6MiB github_issues_medium.csv
    [2019-07-19 12:11:37 PDT]     62B test.csv
```

As far as I understand, this suppose to work:

```
$ mc rm local/master.raw_data/test.csv
Removing `local/master.raw_data/test.csv`.
mc: <ERROR> Failed to remove `local/master.raw_data/test.csv`. This functionality is not implemented in the pachyderm s3gateway.
```
 But it does not.

**What you expected to happen?**:
The `test.csv` file to be delete from the repo.
**How to reproduce it (as minimally and precisely as possible)?**:
1. Install MinIO client and server.
2. Deploy Pachyderm.
3. Create a repo.
4. Put a file to the repo by using `mc cp path-to-file` command.
5. Try to delete the file by using `mc rm path-to-file`
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:36:43Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Pachyderm CLI and pachd server version (use `pachctl version`):
$ pachctl version
COMPONENT           VERSION
pachctl             1.9.0
pachd               1.9.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
$ minikube version
minikube version: v0.35.0
- OS (e.g. from /etc/os-release):
macOS
- Others:

### LINKED ISSUE #4005: s3gateway: better errors when attempting to write to an output repo
Currently s3gateway serves an InternalError when attempting to write to an output repo. A better, custom error should be served instead.

### PR DESCRIPTION
**Pull request by ysimonson**
A number of refactors/improvements to s3gateway:
* Added support for multipart uploads (closes #3903)
* Added request/response timeouts to HTTP requests (closes #3892)
* Added partial support for versioning (closes #3902)
* Added support for multi-object delete (closes #3930)
* Better error messages when attempting to modify an output repo (closes #4005)
* Use new s2 interfaces, which are designed to have fewer footguns
* Aligned API docs to be closer to s3's

### CODE REVIEW

File: src/server/pfs/s3/bucket.go [hunk 1]
```diff
@@ -43,50 +43,62 @@ type bucketController struct {
...
+	location = globalLocation
+	return
 }
 
-func (c bucketController) List(r *http.Request, bucket string, result *s2.ListBucketResult) error {
+func (c *bucketController) ListObjects(r *http.Request, bucket, prefix, marker, delimiter string, maxKeys int) (contents []s2.Contents, commonPrefixes []s2.CommonPrefixes, isTruncated bool, err error) {
 	repo, branch, err := bucketArgs(r, bucket)
 	if err != nil {
-		return err
+		return
```
Comment (jdoliner) [inline src/server/pfs/s3/bucket.go]: Using named return values is generally frowned upon because it's easy to shoot yourself in the foot with them, I've done it several times. The only time we use them is if we need to return errors from deferred functions. Here's an example of how things can go wrong:

```golang
package main

import (
	"fmt"
)

func foo() (err error) {
	if true {
		x, err := 1, fmt.Errorf("error")
		fmt.Printf("x: %d\n", x)
		fmt.Printf("err: %v\n", err)
	}
	return
}

func main() {
	fmt.Println(foo())
}
```

It seems like you're returning the error but you're actually not because of scoping rules. Afaict everything you're doing here is fine, but I had to spend a while staring at it to convince myself that there weren't any scoping issues like this, so I think it'd be clearer if you just returned errors normally.

Comment (ysimonson) [reply src/server/pfs/s3/bucket.go]: After continuing to build on these new interface definitions, I very much agree. But given all the stuff in-flight that builds upon names return values, do you mind if we punt on this in favor of fixing after the current PRs are merged?

Comment (jdoliner) [reply src/server/pfs/s3/bucket.go]: It makes me a little nervous, I've merged a lot of code planning to clean it up eventually and then forgotten to. If you feel like it would derail your progress though I'm ok with punting, this is definitely something that should get cleaned up though.

**Comment by ysimonson** [comment]
I built the other two PRs you reviewed on this one, so unfortunately I'd save a great deal of time by addressing the return values after. But I'll make sure to address it immediately after these are merged: https://github.com/pachyderm/s2/issues/14

**Comment by ysimonson** [comment]
Per offline discussion, we're going to use this PR for all the in-flight s3gateway improvements. That way, I can also address the interface fixes before it lands on master.

**Comment by ysimonson** [comment]
@jdoliner all changes are in, ready for another pass

File: src/server/pfs/s3/multipart.go [hunk 2]
```diff
@@ -0,0 +1,412 @@
...
+
+	repo = match[1]
+	branch = match[2]
+	key = match[3]
+	uploadID = match[4]
+	return
+}
+
+func parentDirPath(repo, branch, key, uploadID string) string {
+	return fmt.Sprintf("%s/%s/%s/%s", repo, branch, key, uploadID)
```
Comment (jdoliner) [inline src/server/pfs/s3/multipart.go]: For path construction I'd recommend using the `path` package, for one it's a tad shorter, this would be written as `path.Join(repo, branch, key, uploadID)` but more importantly without it I'm always worried I'll accidentally wind up with a double slash or a missing slash, whereas with `path.Join` you don't have to think about it.

File: src/server/pfs/s3/multipart.go [hunk 3]
```diff
@@ -0,0 +1,412 @@
...
+	return fmt.Sprintf("%s/.keep", parentDirPath(repo, branch, key, uploadID))
+}
+
+func (c *controller) ensureRepo(pc *client.APIClient) error {
+	_, err := pc.InspectBranch(c.repo, "master")
+	if err != nil {
+		err = pc.CreateRepo(c.repo)
+		if err != nil && !strings.Contains(err.Error(), "as it already exists") {
+			return err
+		}
```
Comment (jdoliner) [inline src/server/pfs/s3/multipart.go]: Use `UpdateRepo` (you can add a method for it in `src/client/pfs.go` or just call it directly) it supports upsert behavior so you won't have to do an awkward error check.

File: src/server/pfs/s3/multipart.go [hunk 4]
```diff
@@ -0,0 +1,412 @@
...
+
+		err = pc.CreateBranch(c.repo, "master", "", nil)
+		if err != nil && !strings.Contains(err.Error(), "as it already exists") {
+			return err
+		}
```
Comment (jdoliner) [inline src/server/pfs/s3/multipart.go]: Similarly, I think you can drop this error filter since `CreateBranch` allows you to update branches by default since that's such a common operation.

File: src/server/pfs/s3/multipart.go (hunk 3 above)
Comment (ysimonson) [reply src/server/pfs/s3/multipart.go]: That doesn't seem to exist any longer in `pfs.proto`. Want me to still add a higher-level method in `src/client/pfs.go`?

Comment (ysimonson) [reply src/server/pfs/s3/multipart.go]: Oh I see, `CreateRepo` can take an update parameter

**Comment by ysimonson** [comment]
@jdoliner issues addressed, ready for another pass

File: src/server/pfs/s3/s3.go [hunk 5]
```diff
@@ -79,17 +85,25 @@ func Server(pc *client.APIClient, port uint16) *http.Server {
...
 			now := time.Now()
 			if !isEnterprise || now.Sub(lastEnterpriseCheck) > enterpriseTimeout {
+				vars := mux.Vars(r)
+				pc, err := c.pachClient(vars["authAccessKey"])
+				if err != nil {
+					err = fmt.Errorf("gRPC client client: %v", err)
+					s2.WriteError(logger, w, r, s2.InternalError(r, err))
+					return
+				}
+				defer pc.Close()
```
Comment (jdoliner) [inline src/server/pfs/s3/s3.go]: Handle this error?

File: src/server/pkg/errutil/errutil.go [hunk 6]
```diff
@@ -30,3 +30,20 @@ func IsNotFoundError(err error) bool {
...
+}
+
+// IsHasNoHeadError returns true if the err is due to an operation that cannot
+// be performed on a headless branch
+func IsHasNoHeadError(err error) bool {
+	if err == nil {
+		return false
+	}
+	return strings.Contains(err.Error(), "has no head")
+}
```
Comment (jdoliner) [inline src/server/pkg/errutil/errutil.go]: This error is defined in `src/server/pfs/pfs.go` along with a bunch of error predicates for detecting the other errors in that file. I'd add this predicate there, rather than here so it'll get updated if the error changes.

**Comment by ysimonson** [comment]
Changes addressed, ready for another pass

File: src/server/pkg/errutil/errutil.go [hunk 7]
```diff
@@ -30,3 +30,11 @@ func IsNotFoundError(err error) bool {
...
 	return strings.Contains(err.Error(), "not found")
 }
+
+// IsInvalidNameError returns true if err is due to an invalid name
+func IsInvalidNameError(err error) bool {
+	if err == nil {
+		return false
+	}
+	return strings.Contains(err.Error(), "only alphanumeric characters, underscores, and dashes are allowed")
+}
```
Comment (jdoliner) [inline src/server/pkg/errutil/errutil.go]: Could we move this predicate to `src/server/pkg/ancestry/ancestry.go` for same reason we relocated the other one. It seems like there's a particular risk of this one changing since it enumerates the valid characters.
