### PR TITLE
Fix #1085

### LINKED ISSUE #1085: A pipeline can only process one branch
A pipeline is supposed to process all branches in a repo.  However, currently it only processes one branch.

Steps to reproduce:

1. Create a repo `test`
2. Create a pipeline that takes `test` as input
3. Create a commit on branch `foo`
4. Observe that a job is spawned and run successfully.
5. Create a commit on branch `bar`
6. Observe that no job is created.

Cause:

The code is blocked on [this line](https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/server/api_server.go#L1551) waiting for a new commit on branch `foo`, unable to detect that a new commit has been added to branch `bar`.

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #1085

### CODE REVIEW

File: src/server/pfs/cmds/cmds.go [hunk 1]
```diff
@@ -244,6 +244,8 @@ Examples:
 
 	var all bool
 	var block bool
+	var listCommitInclude cmd.RepeatedStringArg
+	var listCommitExclude cmd.RepeatedStringArg
 	var listCommitProvenance cmd.RepeatedStringArg
 	listCommit := &cobra.Command{
 		Use:   "list-commit repo-name",
```
Comment (jdoliner) [inline src/server/pfs/cmds/cmds.go]: This usage string is wrong now isn't it since you can't do a repo-name without a `-i` before it right? I think rather than changing it to match the behavior it might make more sense to change the behavior. What if we made it so that positional arguments are interpreted as `include` commits and you only need a flag for exclusion? This is how a number of git commands work. Also I think `-x` for exclude might be more intuitive than `-e` what do you think?

File: src/server/pfs/db/driver.go [hunk 2]
```diff
@@ -798,41 +798,56 @@ func (d *driver) rawCommitToCommitInfo(rawCommit *persist.Commit) *pfs.CommitInf
...
 		}
+		return nil
+	}
+
+	if err := buildQueries(include, "include"); err != nil {
+		return nil, err
+	}
+	if err := buildQueries(exclude, "exclude"); err != nil {
+		return nil, err
+	}
```
Comment (jdoliner) [inline src/server/pfs/db/driver.go]: The control flow in this function seems a little bit weird / confusing to me. What would you think of doing something like:

```go
for i, commit := range append(include, exclude...) {
  // do stuff for all commits
  if i < len(include) {
    // do stuff for include commits 
  } else {
    // do stuff for exclude commits
  }
}
```

that seems a lot simpler to me.

Comment (derekchiang) [inline src/server/pfs/db/driver.go]: Good point.  I like this better.

**Comment by jdoliner** [comment]
1epkgz
