### PR TITLE
Prevent the creation of pipelines with invalid names

### LINKED ISSUE #3216: malformed pipeline name not validated on creation
**What happened?**:
I accidentally created a pipeline with a malformed name and am now unable to delete it.

**What you expected to happen?**:
I think `pachctl` should throw an error instead of creating the pipeline.

**How to reproduce it (as minimally and precisely as possible)?**:
```
$ cat <<-EOF > edges.json
{
  "pipeline": {
    "name": "edges-"
  },
  "transform": {
    "cmd": [ "python3", "/edges.py" ],
    "image": "pachyderm/opencv"
  },
  "input": {
    "atom": {
      "repo": "images",
      "glob": "/*"
    }
  }
}
EOF

$ pachctl create-pipeline -f edges.json

$ pachctl list-pipeline
NAME    INPUT     OUTPUT         CREATED        STATE
edges-  images:/* edges-/master  11 seconds ago starting

$ pachctl delete-pipeline edges-
error deleting workers: unable to parse requirement: invalid label value: "edges-": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end
with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```
$ pachctl version
COMPONENT           VERSION             
pachctl             1.7.10              
pachd               1.7.10
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
```
local deployment
```
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="18.09.1023.06fb0253afa (Jellyfish)"
VERSION_CODENAME=jellyfish
VERSION_ID="18.09.1023.06fb0253afa"
PRETTY_NAME="NixOS 18.09.1023.06fb0253afa (Jellyfish)"
HOME_URL="https://nixos.org/"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```
- Others:

### PR DESCRIPTION
**Pull request by ysimonson**
Fixes #3216 by validating the pipeline name when created

I'm not sure if this is the right fix; #3216 implies to me that we're not propagating errors triggered by the creation of the pod (including invalid labels.) Is this on purpose?

### CODE REVIEW

File: src/server/pps/server/api_server.go [hunk 1]
```diff
@@ -180,6 +182,10 @@ func validateNames(names map[string]bool, input *pps.Input) error {
 }
 
 func (a *apiServer) validateInput(pachClient *client.APIClient, pipelineName string, input *pps.Input, job bool) error {
+	if !pipelineNameMatcher.MatchString(pipelineName) {
+		return fmt.Errorf("Invalid pipeline name: a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345')")
+	}
+
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: This would be better placed in `validatePipeline` than `validateInput` since the validation isn't specific to inputs.

File: src/server/pps/server/api_server.go [hunk 2]
```diff
@@ -180,6 +182,10 @@ func validateNames(names map[string]bool, input *pps.Input) error {
 }
 
 func (a *apiServer) validateInput(pachClient *client.APIClient, pipelineName string, input *pps.Input, job bool) error {
+	if !pipelineNameMatcher.MatchString(pipelineName) {
+		return fmt.Errorf("Invalid pipeline name: a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345')")
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: Referring to this as a `label` is probably going to be confusing to users who get it back. Also we should probably disallow empty strings for pipeline names, I can't think of a real use case for that.
