### PR TITLE
Make flush job --raw streaming.

### LINKED ISSUE #4567: Job/commit flushing does not stream results back
With the exception of `flush commit --raw`, `pachctl`'s `flush job` and `flush commit` commands do not stream results back as subvenant commits are finished. Instead, they return all of the results when the entire flush operation is complete.

### PR DESCRIPTION
**Pull request by jdoliner**
Fixes #4567

### CODE REVIEW

File: src/server/pps/cmds/cmds.go [hunk 1]
```diff
@@ -241,29 +244,27 @@ $ {{alias}} foo@XXX -p bar -p baz`,
...
+				writer = tabwriter.NewWriter(os.Stdout, pretty.JobHeader)
 			}
-
-			if raw {
-				e := encoder(output)
-				for _, jobInfo := range jobInfos {
-					if err := e.EncodeProto(jobInfo); err != nil {
+			if err := c.FlushJob(commits, pipelines, func(ji *ppsclient.JobInfo) error {
+				if raw {
+					e := encoder(output)
```
Comment (ysimonson) [inline src/server/pps/cmds/cmds.go]: Is there any overhead to repeatedly cresting an encoder?

**Comment by ysimonson** [comment]
Lgtm, just a question

File: src/server/pps/cmds/cmds.go (hunk 1 above)
Comment (jdoliner) [reply src/server/pps/cmds/cmds.go]: Very minimal, it's basically just a dumb struct, which when gets some options applied to it. But I'll move it outside anyways since who knows if that'll change, and might as well do the faster thing if there's no added complexity.
