### PR TITLE
Fixes several issues with `--split` including etcd txn limit

### LINKED ISSUE #1538: Using `put-file --split` with a file that has many datums results in "etcdserver: too many operations in txn request"
Using `put-file --split` with a file that has many datums results in the error:

```
etcdserver: too many operations in txn request
```

### PR DESCRIPTION
**Pull request by jdoliner**
Fixes #1538

### CODE REVIEW

File: src/server/pfs/server/driver.go [hunk 1]
```diff
@@ -25,14 +26,56 @@ import (
...
+type CommitStream interface {
+	Stream() <-chan CommitEvent
+	Close()
+}
+
 type collectionFactory func(string) col.Collection
 
-type driver struct {
+// Driver implements the underlying pfs semantics.
+type Driver struct {
```
Comment (derekchiang) [inline src/server/pfs/server/driver.go]: Looks like you made all the methods on `Driver` private.  If that's the case, should we make `Driver` private too?

File: src/server/pfs/server/driver.go [hunk 2]
```diff
@@ -476,17 +513,43 @@ func (d *driver) FinishCommit(ctx context.Context, commit *pfs.Commit) error {
 			if err := tree.DeleteFile(filePath); err != nil {
 				// Deleting a non-existent file in an open commit should
 				// be a no-op
-				if !(hashtree.Code(err) == hashtree.PathNotFound) {
+				if hashtree.Code(err) != hashtree.PathNotFound {
```
Comment (derekchiang) [inline src/server/pfs/server/driver.go]: lol

File: src/server/pfs/server/driver.go [hunk 3]
```diff
@@ -476,17 +513,43 @@ func (d *driver) FinishCommit(ctx context.Context, commit *pfs.Commit) error {
...
 		} else {
-			var objectHash string
-			var size int64
-			fmt.Sscanf(string(kv.Value), "%d %s", &size, &objectHash)
-			if err := tree.PutFile(filePath, []*pfs.Object{{Hash: objectHash}}, size); err != nil {
+			records := &PutFileRecords{}
+			if err := proto.Unmarshal(kv.Value, records); err != nil {
 				return err
 			}
+			if !records.Split {
```
Comment (derekchiang) [inline src/server/pfs/server/driver.go]: I don't completely understand how this works so just checking, but would you end up with more than one record without `--split` if you call `PutFile` on the same file twice?

File: src/server/pfs/server/driver.go [hunk 4]
```diff
@@ -476,17 +513,43 @@ func (d *driver) FinishCommit(ctx context.Context, commit *pfs.Commit) error {
...
+					return err
+				}
+			} else {
+				nodes, err := tree.List(filePath)
+				if err != nil && hashtree.Code(err) != hashtree.PathNotFound {
+					return err
+				}
+				var indexOffset int64
+				if len(nodes) > 0 {
+					indexOffset, err = strconv.ParseInt(path.Base(nodes[len(nodes)-1].Name), 16, 64)
```
Comment (derekchiang) [inline src/server/pfs/server/driver.go]: Should we make these magic numbers into constants?  Wasn't sure what they were at first glance.

File: src/server/pfs/server/driver.go [hunk 5]
```diff
@@ -476,17 +513,43 @@ func (d *driver) FinishCommit(ctx context.Context, commit *pfs.Commit) error {
...
+					if err != nil {
+						return fmt.Errorf("error parsing filename %s as int, this likely means you're "+
+							"using split on a directory which contains other data that wasn't put with split",
+							path.Base(nodes[len(nodes)-1].Name))
+					}
+					indexOffset++ // start writing to the file after the last file
+				}
+				for i, record := range records.Records {
+					if err := tree.PutFile(path.Join(filePath, fmt.Sprintf("%016x", i+int(indexOffset))), []*pfs.Object{{Hash: record.ObjectHash}}, record.SizeBytes); err != nil {
```
Comment (derekchiang) [inline src/server/pfs/server/driver.go]: Presumably you'd use the aforementioned constant in place of the `16` here.

File: src/server/pkg/hashtree/interface.go [hunk 6]
```diff
@@ -82,6 +82,7 @@ type OpenNode struct {
 // updated (until then, the hashes and sizes stored in an OpenHashTree will be
 // stale).
 type OpenHashTree interface {
+	HashTree
```
Comment (derekchiang) [inline src/server/pkg/hashtree/interface.go]: As mentioned offline, I'm not sure if an `OpenHashTree` returns the right sizes for its internal nodes.  Can @msteffen confirm?  Regardless, the usage in this patch should work since we are not really using sizes.

File: src/server/pfs/server/driver.go (hunk 2 above)
Comment (jdoliner) [inline src/server/pfs/server/driver.go]: Freed up a pair of parentheses and an equals sign for use elsewhere in the cluster.

File: src/server/pfs/server/driver.go (hunk 1 above)
Comment (jdoliner) [inline src/server/pfs/server/driver.go]: I can, I'll have to rejigger how it gets instantiated a bit but shouldn't be too hard.

File: src/server/pfs/server/driver.go (hunk 3 above)
Comment (jdoliner) [inline src/server/pfs/server/driver.go]: In that case you'd get 2 records, there's a 1-to-1 correspondence between records and `put-file` requests.

File: src/server/pfs/server/driver.go (hunk 4 above)
Comment (jdoliner) [inline src/server/pfs/server/driver.go]: Sure, will do.
