### PR TITLE
Fixes bug when doing get file on an empty file

### LINKED ISSUE #2954: Worker unable to find datum's file
**What happened?**:
From a fresh cluster:

- created a repo
- created a pipline consuming that repo
- added a file to the input repo
- created a pipeline consuming that repo's output
- got an error in the second pipeline's job:

```
starting to download data
errored downloading data after 56.710088ms: no file(s) found that match a4950c97c30b41c85979d7f4d5a7cbcb12a3c66ff9a3d74e2a30fe955e0de776/job:8da4166919504001b5a03f57d6a027ac
failed processing datum: error downloadData: no file(s) found that match a4950c97c30b41c85979d7f4d5a7cbcb12a3c66ff9a3d74e2a30fe955e0de776/job:8da4166919504001b5a03f57d6a027ac, retrying in 0s
starting to download data
errored downloading data after 46.287879ms: no file(s) found that match a4950c97c30b41c85979d7f4d5a7cbcb12a3c66ff9a3d74e2a30fe955e0de776/job:8da4166919504001b5a03f57d6a027ac
failed processing datum: error downloadData: no file(s) found that match a4950c97c30b41c85979d7f4d5a7cbcb12a3c66ff9a3d74e2a30fe955e0de776/job:8da4166919504001b5a03f57d6a027ac, retrying in 0s
starting to download data
errored downloading data after 46.357294ms: no file(s) found that match a4950c97c30b41c85979d7f4d5a7cbcb12a3c66ff9a3d74e2a30fe955e0de776/job:8da4166919504001b5a03f57d6a027ac
failed to process datum with error: error downloadData: no file(s) found that match a4950c97c30b41c85979d7f4d5a7cbcb12a3c66ff9a3d74e2a30fe955e0de776/job:8da4166919504001b5a03f57d6a027ac
```

**What you expected to happen?**:

Job runs fine

**How to reproduce it (as minimally and precisely as possible)?**:

```
pachctl create-repo input
echo '{
  "pipeline": {
    "name": "test"
  },
  "transform": {
    "cmd": [ "bash", "-c", "cp -r $(ls -d /pfs/*|grep -v /pfs/out) /pfs/out" ]
  },
  "input": {
    "atom": {
      "repo": "input",
      "branch": "master",
      "glob": "*"
    }
  },
  "enable_stats": true
}' | pachctl create-pipeline
echo hello | pachctl put-file input master /0
echo '{
  "pipeline": {
    "name": "test2"
  },
  "transform": {
    "cmd": [ "bash", "-c", "cp -r $(ls -d /pfs/*|grep -v /pfs/out) /pfs/out" ]
  },
  "input": {
    "atom": {
      "repo": "test",
      "branch": "stats",
      "glob": "*"
    }
  }
}' | pachctl create-pipeline
```
Wait a few seconds for jobs to run, then `pachctl list-job --pipeline test2` and observe a failure

**Anything else we need to know?**:

Full `storage` container logs: 
[lotsalogs.txt](https://github.com/pachyderm/pachyderm/files/2033514/lotsalogs.txt)

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
(deployed with `make launch-kube`)

- Pachyderm CLI version (use `pachctl version`):

```
$ pc version
COMPONENT           VERSION                                          
pachctl             1.7.3-14105af189aa929c25e539266b30d47877217ba7   
pachd               1.7.3-14105af189aa929c25e539266b30d47877217ba7
```
(deployed with `make launch-dev`)

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
local (`vm-driver=none`)

### PR DESCRIPTION
**Pull request by brycemcanally**
Fixes #2954

### CODE REVIEW

File: src/server/pfs/server/driver.go [hunk 1]
```diff
@@ -2194,8 +2194,11 @@ func (d *driver) getFile(ctx context.Context, file *pfs.File, offset int64, size
 	if err != nil {
 		return nil, err
 	}
+	if len(paths) <= 0 {
+		return nil, fmt.Errorf("no file(s) found that match %v", file.Path)
+	}
 
-	var objects []*pfs.Object
+	objects := []*pfs.Object{}
```
Comment (jdoliner) [inline src/server/pfs/server/driver.go]: Any reason you changed this? Doing it with `var` is more standard for our codebase. And it's slightly shorter, 25 characters vs 26, think of all the bits we'll save.
