### PR TITLE
Fix TestPipelineBuildLifecycle & fix race in PutFile

### LINKED ISSUE #5345: TestPipelineBuildLifecycleGo flake
TestPipelineBuildLifecycleGo failed in https://travis-ci.com/github/pachyderm/pachyderm/jobs/399167346

```
=== RUN   TestPipelineBuildLifecycleGo
../../../../etc/testing/pipeline-build/input/111.txt: 3 B / 3 B  100.00% ? p/s 0
../../../../etc/testing/pipeline-build/input/1.txt: 1 B / 1 B [ 100.00% ? p/s 0s
../../../../etc/testing/pipeline-build/input/11.txt: 2 B / 2 B  100.00% ? p/s 0s
go.mod: 131 B / 131 B [=======================================] 100.00% ? p/s 0s
go.sum: 169 B / 169 B [=======================================] 100.00% ? p/s 0s
main.go: 795 B / 795 B [======================================] 100.00% ? p/s 0s
file /1.txt not found in repo test-pipeline-build at commit d4ec0aec17fa49248db2a5d388e5bfc1
failed to find
  "0001"
in the text:
  """
  """
```

### PR DESCRIPTION
**Pull request by msteffen**
Fix #5345 

Summary: `TestPipelineBuildLifecycleGo` (and `...Python`, etc) were flaking due to an encoutering a race in PutFile. The race is this: `putFile` reads its incoming stream of `PutFileRequest`s using `forEachPutFile`, and `forEachPutFile` spawns a goroutine for each new file in the incoming stream. When multiple independent files are being written, e.g. `/a`, `/b`, ..., `forEachPutFile` spawns a concurrent goroutine to write each of them. This works well and gives us good throughput, as `forEachPutFile` can read data from the incoming stream while child goroutines are waiting for object storage to finish writing.

However, when conflicting operations are sent in the same stream, e.g. `Delete(/)` -> `Put(/src.go)` as in `TestPipelineBuildLifecycle*`, the Go scheduler might choose to run `eg.Go(Put(/src.go))` first, even though it was spawned second, causing `/src.go` to be written and then immediately deleted by `Delete(/)`.

This PR attempts to fix the issue by introducing a new class, `pathlock`, that blocks `forEachPutFile` from running a new operation as long as a conflicting operation (on a parent or child path) is already in progress. Basically, `forEachPutFile` would call `start("/")` and that would block `start("/src.go")` from running (becuase `/src.go` is a child of `/`) until `finish("/")` is called. (Likewise, if the operations were deliberately performed in the reverse order, `start("/src.go")` would block `start("/")` until `finish("/src.go")` is called)

A simpler solution might be to remove all concurrency from `forEachPutFile`, but my understanding is that that would unacceptably hurt `PutFile` throughput. Given that constraint, I tried to keep this simple by only allowing `pathlock.start()` to block a single goroutine at a time (so it works for `forEachPutFile` but not much else, and stays in the `pfs/server` package). A comment in `pathlock.go` elaborates on this constraint.

A few other changes also made in this PR:
- `make lint` was failing silently (which @nitinjainsj found) in CI due to a prior change I made. This PR should fix it
- `PutFile` now writes Debug-level logs at both the start and end of writing/deleting a file within the stream (and the logs are changed to look more like our regular GRPC logs)

### CODE REVIEW

File: src/server/pfs/server/driver.go [hunk 1]
```diff
@@ -4805,18 +4851,30 @@ func (d *driver) forEachPutFile(pachClient *client.APIClient, server pfs.API_Put
...
 			pr := pr
-			d.putFileLimiter.Acquire()
-			eg.Go(func() error {
-				defer d.putFileLimiter.Release()
+			if err := pl.start(req.File.Path); err != nil {
+				return false, "", "", errors.Wrapf(err, "could not lock path %q", req.File.Path)
+			}
+			eg.Go(func() (retErr error) {
+				defer func() {
+					if err := pl.finish(req.File.Path); err != nil && retErr == nil {
```
Comment (brendoncarroll) [inline src/server/pfs/server/driver.go:4874]: Is it possible for this call to `finish` and the one above to both be executed for a path? Is that okay?

File: src/server/pfs/server/pathlock.go [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+	if minGe == len(p.running) || p.running[minGe] != path {
+		return errors.Errorf("no path lock found for PutFile operation on %q", path)
+	}
+	copy(p.running[minGe:], p.running[minGe+1:]) // OK even if (minGe+1) == len(running)
+	p.running = p.running[:len(p.running)-1]
+
+	// Wake up any blocked threads
+	if p.blocking == path {
+		p.blocking = "" // reset block
+		// Both Signal() and Broadcast() *should* be safe, b/c there should only
```
Comment (brendoncarroll) [inline src/server/pfs/server/pathlock.go:134]: 👍

File: src/server/pfs/server/driver.go (hunk 1 above)
Comment (msteffen) [reply src/server/pfs/server/driver.go:4874]: The goal (though I may have made a mistake) is that each `finish` call is tied to a `start` call above it, so as long as the sequence is `start(/a)->finish(/a)->start(/a)->finish(/a)`[1]  I think it should all be fine. If `finish` is called with no corresponding start then I think it would return an error when it couldn't find the path in its list of pending operations (which I think would cause `PutFile` to return an error)

[1] or, equivalently `start(/a)->start(/a) <block> -> finish(/a) -> start(/a) <unblock> -> finish(/a)`

File: src/server/pfs/server/pathlock.go [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+	p := pathlock{
+		putFileLimiter: putFileLimiter,
+	}
+	p.Cond.L = &p.Mutex
+	return &p
+}
+
+func (p *pathlock) start(path string) (retErr error) {
+	// add leading slash, so '/' collides w/ everything.
+	// TODO(msteffen): would paths.go (in this package) or s/s/pkg/paths be
```
Comment (brendoncarroll) [inline src/server/pfs/server/pathlock.go:57]: For the storage v1 I think we use the clean from the hashtree package?

**Review by brendoncarroll — APPROVED** [review]
My only concern is that it is not obvious that each start corresponds to a finish in `forEachPutFile` if that could be refactored to use a switch for the various operations and have one start and one finish above and below that would be better.  We will probably revisit this code for StorageV2, so if there's no clear path to make that change now, then I say okay to merge as is.

File: src/server/pfs/server/driver.go [hunk 4]
```diff
@@ -3013,17 +3015,45 @@ func (d *driver) scratchFilePrefix(file *pfs.File) (string, error) {
...
+		start := time.Now()
+		var records *pfs.PutFileRecords
+		logPutFileStart(req)
+		defer func() { logPutFileEnd(req, start, records, retErr) }() //late binding
+		records, retErr = d.putFile(pachClient, req.File, req.Delimiter, req.TargetFileDatums,
 			req.TargetFileBytes, req.HeaderRecords, req.OverwriteIndex, req.Delete, r)
-		if err != nil {
-			return err
+		if retErr != nil {
+			return retErr
```
Comment (jdoliner) [inline src/server/pfs/server/driver.go:3056]: Using `retErr` outside of a defer makes me a little uneasy. I've gotten burned by some bad scoping things in the past. Could we make this back to being a a new `err` that gets returned?

**Review by jdoliner — APPROVED** [review]
LGTM, one small request about a usage of named return parameters.

File: src/server/pfs/server/pathlock.go (hunk 3 above)
Comment (msteffen) [reply src/server/pfs/server/pathlock.go]: :+1: I went through the process of trying to use that, and it actually ended up being a bit longer and more complicated than this (i.e. `"/"+strings.TrimPrefix(hashtree.Clean("/"+path), "/")`) so I decided to just remove the todo. Let me know if you think it's worth using hashtree anyway, but I figured shorter is better (and I removed the TODO)

File: src/server/pfs/server/driver.go (hunk 4 above)
Comment (msteffen) [reply src/server/pfs/server/driver.go]: Done

**Comment by msteffen** [comment]
> My only concern is that it is not obvious that each start corresponds to a finish in `forEachPutFile` if that could be refactored to use a switch for the various operations and have one start and one finish above and below that would be better. We will probably revisit this code for StorageV2, so if there's no clear path to make that change now, then I say okay to merge as is.

I see your point—my feeling is that this would be a fairly significant rewrite of `forEachPutFile`, so my instinct is to do that separately, but I definitely think it's warranted. If I see a good way to rewrite that, I'll go for it (I think it'll be similar to some of the merging code, in that we'll need some helpers for the different PutFile branches—URL, object storage, etc—and the ability to peek ahead into the stream to decide which one to use)
