### PR TITLE
Widen retry logic in PPS master.

### LINKED ISSUE #5557: Pipeline events during deletion can lead to failing a pipeline incorrectly.
CI hung on TestStatsDeleteAll here: https://app.circleci.com/pipelines/github/pachyderm/pachyderm/1522/workflows/260fb0b5-3c2a-4e42-8a35-6c14d2698b86/jobs/21587

It looks like pipeline polling attempted to update the pipeline RC after it had already been deleted. By the time the retry loop was exhausted, a pipeline with the same name had been created, which was then failed by the PPS master logic while the new pipeline was still STARTING. 

```
2020-12-23T22:25:40Z INFO pps.API.DeleteAll {"request":{}} []
2020-12-23T22:25:40Z INFO pps.API.DeletePipeline {"request":{"all":true,"force":true}} []2020-12-23T22:25:40Z INFO PPS master: deleting resources for pipeline "pipeline2bcab378109f"
2020-12-23T22:25:40Z INFO PPS master: processing event for "pipeline2bcab378109f"
...
2020-12-23T22:25:40Z INFO PPS master: scaling up workers for "pipeline2bcab378109f"
2020-12-23T22:25:40Z INFO PPS master: monitoring pipeline "pipeline2bcab378109f"
2020-12-23T22:25:41Z INFO PPS master: processing event for "pipeline2bcab378109f"
2020-12-23T22:25:42Z ERROR PPS master: error updating RC for pipeline "pipeline2bcab378109f": Operation cannot be fulfilled on replicationcontrollers "pipeline-pipeline2bcab378109f-v1": StorageError: invalid object, Code: 4, Key: /registry/controllers/default/pipeline-pipeline2bcab378109f-v1, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2033fbaf-060b-4e50-b5a5-185862c0a007, UID in object meta: ; retrying in 466.968022ms
2020-12-23T22:25:42Z INFO pps.API.DeleteJob {"request":{"job":{"id":"f565f2eba55b40509311a36dfc340f97"}}} []
2020-12-23T22:25:42Z INFO pfs.API.FinishCommit {"request":{"commit":{"repo":{"name":"pipeline2bcab378109f"},"id":"76e07afcb8394d909eae63e04e663110"},"empty":true}} []
2020-12-23T22:25:42Z ERROR pfs.API.FinishCommit {"duration":0.000649411,"error":"commit 76e07afcb8394d909eae63e04e663110 not found in repo pipeline2bcab378109f","request":{"commit":{"repo":{"name":"pipeline2bcab378109f"},"id":"76e07afcb8394d909eae63e04e663110"},"empty":true},"response":null,"stack":null} []
2020-12-23T22:25:42Z INFO pps.API.DeleteJob {"duration":0.003062594,"request":{"job":{"id":"f565f2eba55b40509311a36dfc340f97"}},"response":{}} []
2020-12-23T22:25:42Z INFO pfs.API.DeleteBranch {"request":{"branch":{"repo":{"name":"__spec__"},"name":"pipeline2bcab378109f"},"force":true}} []
2020-12-23T22:25:42Z INFO pfs.API.DeleteBranch {"duration":0.002135654,"request":{"branch":{"repo":{"name":"__spec__"},"name":"pipeline2bcab378109f"},"force":true},"response":{}} []
2020-12-23T22:25:42Z INFO pps.API.DeletePipeline {"duration":1.909757801,"request":{"pipeline":{"name":"pipeline2bcab378109f"},"all":true,"force":true},"response":{}} []
2020-12-23T22:25:42Z INFO pfs.API.DeleteRepo {"request":{"repo":{"name":"__spec__"},"force":true}} []
2020-12-23T22:25:42Z INFO pfs.API.DeleteRepo {"duration":0.002667767,"request":{"repo":{"name":"__spec__"},"force":true},"response":{}} []
2020-12-23T22:25:42Z INFO pfs.API.CreateRepo {"request":{"repo":{"name":"__spec__"},"description":"PPS pipeline specs repo.","update":true}} []
2020-12-23T22:25:42Z INFO pfs.API.CreateRepo {"duration":0.001782221,"request":{"repo":{"name":"__spec__"},"description":"PPS pipeline specs repo.","update":true},"response":{}} []
2020-12-23T22:25:42Z INFO pps.API.DeleteAll {"duration":2.308732472,"request":{},"response":{}} []
2020-12-23T22:25:42Z INFO pfs.API.DeleteAll {"request":{}} []
2020-12-23T22:25:42Z INFO pfs.API.DeleteAll {"duration":0.00305091,"request":{},"response":{}} []
2020-12-23T22:25:42Z INFO transaction.API.DeleteAll {"request":{}} []
2020-12-23T22:25:42Z INFO transaction.API.DeleteAll {"duration":0.000786041,"request":{},"response":{}} []
2020-12-23T22:25:42Z INFO pfs.API.CreateRepo {"request":{"repo":{"name":"TestPipelineWithStats_data5a8a4d3597b8"}}} []
2020-12-23T22:25:42Z INFO pfs.API.CreateRepo {"duration":0.00136136,"request":{"repo":{"name":"TestPipelineWithStats_data5a8a4d3597b8"}},"response":{}} []
2020-12-23T22:25:42Z INFO pps.API.CreatePipeline {"request":{"pipeline":{"name":"pipeline2bcab378109f"},"transform":{"cmd":["cp","/pfs/TestPipelineWithStats_data5a8a4d3597b8/file","/pfs/out"]},"input":{"pfs":{"repo":"TestPipelineWithStats_data5a8a4d3597b8","glob":"/*"}},"enable_stats":true}} []
2020-12-23T22:25:42Z INFO pps.API.CreatePipeline {"duration":0.028790394,"request":{"pipeline":{"name":"pipeline2bcab378109f"},"transform":{"cmd":["cp","/pfs/TestPipelineWithStats_data5a8a4d3597b8/file","/pfs/out"]},"input":{"pfs":{"repo":"TestPipelineWithStats_data5a8a4d3597b8","glob":"/*"}},"enable_stats":true},"response":{}} []
{"name":"TestPipelineWithStats_data5a8a4d3597b8"},"id":"365b3c728e654e3985d79a405e88994a"}]}} []
2020-12-23T22:25:42Z ERROR PPS master: error updating RC for pipeline "pipeline2bcab378109f": Operation cannot be fulfilled on replicationcontrollers "pipeline-pipeline2bcab378109f-v1": StorageError: invalid object, Code: 4, Key: /registry/controllers/default/pipeline-pipeline2bcab378109f-v1, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2033fbaf-060b-4e50-b5a5-185862c0a007, UID in object meta: ; retrying in 666.898802ms
2020-12-23T22:25:43Z INFO SetPipelineState attempting to move pipeline2bcab378109f to PIPELINE_FAILURE
2020-12-23T22:25:43Z INFO SetPipelineState moving pipeline pipeline2bcab378109f from PIPELINE_STARTING to PIPELINE_FAILURE
2020-12-23T22:25:43Z ERROR PPS master: error scaling up: failing pipeline "pipeline2bcab378109f": failed to update RC after 3 attempts: Operation cannot be fulfilled on replicationcontrollers "pipeline-pipeline2bcab378109f-v1": StorageError: invalid object, Code: 4, Key: /registry/controllers/default/pipeline-pipeline2bcab378109f-v1, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2033fbaf-060b-4e50-b5a5-185862c0a007, UID in object meta:
2020-12-23T22:25:43Z ERROR PPS master: failing pipeline "pipeline2bcab378109f": failed to update RC after 3 attempts: Operation cannot be fulfilled on replicationcontrollers "pipeline-pipeline2bcab378109f-v1": StorageError: invalid object, Code: 4, Key: /registry/controllers/default/pipeline-pipeline2bcab378109f-v1, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 2033fbaf-060b-4e50-b5a5-185862c0a007, UID in object meta:
```

### PR DESCRIPTION
**Pull request by PFedak**
In some cases, a "step" operation failing to complete can indicate that
the underlying pipeline state has changed, making the step obsolete.
Instead of myopically retrying the same operation and eventually
failing, retrying the step from the beginning provides more confidence
that PPS master is acting based on up-to-date information.

Fix #5557

### CODE REVIEW

File: src/server/pps/server/master.go [hunk 1]
```diff
@@ -158,6 +166,31 @@ eventLoop:
...
+		var failError failPipelineError
+		if errors.As(err, &failError) {
+			// don't just return this error, we might have to fail the pipeline
+			if errCount++; errCount >= maxErrCount || !failError.retry {
+				failError := m.a.setPipelineFailure(ctx, e.pipeline, fmt.Sprintf(
+					"could not update resources after %d attempts: %v", errCount, err))
+				if failError != nil {
+					return fmt.Errorf("error failing pipeline %q: %v", e.pipeline, failError)
+				}
+				return fmt.Errorf("failing pipeline %q: %v", e.pipeline, err)
```
[the remark this answers is not in the document]
Comment (msteffen) [reply src/server/pps/server/master.go:184]: Update: after reading the `PIPELINE_FAILURE` section below, another idea I had was to change `failPipelineError` so that failure is optional and then rename it. Perhaps something like:
```
type errRetryStep struct {
  error  // go "inheritance" - field 'error' of type 'error'
  maxRetries int
  failPipelineOnExit bool
}
```
Then if `deletePipelineResources` errors, we can still retry the `step()` call by returning `errRetryStep`, but set `failPipelineOnExit` to `false`. Incidentally, this struct would remove the possible name conflict here.

File: src/server/pps/server/pipeline_controller.go [hunk 2]
```diff
@@ -203,7 +198,11 @@ func (op *pipelineOp) run() error {
 		}
 		// deletePipelineResources calls cancelMonitor() and cancelCrashingMonitor()
 		// in addition to deleting the RC, so those calls aren't necessary here.
-		return op.deletePipelineResources()
+		if err := op.deletePipelineResources(); err != nil {
```
Comment (msteffen) [inline src/server/pps/server/pipeline_controller.go:201]: I actually think we may want to retry deleting the pipeline resources here, if possible (kubernetes might be transiently unavailable). I wrote a suggestion above to change `failPipelineError` to `errRetryStep` that might allow this codepath to be retried in the same way as the others.

If it turns out `errRetryStep` won't work and we can't feasibly retry here, it's not a huge deal because `pollPipelines` should eventually come around and retry itself, but I think `errRetryStep{}` might be an improvement over that, since `pollPipelines` might not come around for a several minutes.

File: src/server/pps/server/master.go [hunk 3]
```diff
@@ -158,6 +166,31 @@ eventLoop:
...
+		return m.step(e.pipeline, e.etcdVer, e.etcdRev)
+	}, backoff.NewInfiniteBackOff(), func(err error, d time.Duration) error {
+		var failError failPipelineError
+		if errors.As(err, &failError) {
+			// don't just return this error, we might have to fail the pipeline
+			if errCount++; errCount >= maxErrCount || !failError.retry {
+				failError := m.a.setPipelineFailure(ctx, e.pipeline, fmt.Sprintf(
+					"could not update resources after %d attempts: %v", errCount, err))
+				if failError != nil {
+					return fmt.Errorf("error failing pipeline %q: %v", e.pipeline, failError)
```
Comment (msteffen) [inline src/server/pps/server/master.go:182]: In general I think we're preferring `error.Wrapf` over `fmt.Errorf(..., err)` (if that works for this code? I think we've been preferring it because it works better with `errors.As`, but maybe that's a problem here?)

**Review by msteffen — COMMENTED** [review]
I had a fair number of suggestions, but overall I think this is a big improvement. I think the new control flow is a lot simpler, and obviously the retry logic is more correct. Nice!

Two broad suggestions I had, which I'm recording here for myself:
- [ ] prefer `errors.Wrap` over `fmt.Errorf(..., err)`
- [ ] comments of the form `Like other functions in this file...` I think can be removed now that the control flow is simpler.

I'm happy to discard these suggestions if you disagree with them, but I just didn't want to forget about them completely.

File: src/server/pps/server/master.go (hunk 3 above)
Comment (PFedak) [reply src/server/pps/server/master.go:182]: Sounds good, I don't think it should affect functionality

File: src/server/pps/server/pipeline_controller.go (hunk 2 above)
Comment (PFedak) [reply src/server/pps/server/pipeline_controller.go:201]: I was hoping you could provide some insight here, thanks. It seemed like the previous code went out of its way to not retry this case, and I wasn't sure I wanted to shove more complexity into the error type. Allowing retry makes sense to me

File: src/server/pps/server/master.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (PFedak) [reply src/server/pps/server/master.go:184]: Agreed that the shadowing is unneeded, not sure why I went that direction. Adding the extra field does seem appropriate for capturing all of the information needed at the top level; I don't think my hesitance to add more was based on any good reason.

File: src/server/pps/server/master.go [hunk 4]
```diff
@@ -158,6 +166,31 @@ eventLoop:
 	}
 }
 
+func (m *ppsMaster) attemptStep(ctx context.Context, e *pipelineEvent) error {
+	var errCount int
+	return backoff.RetryNotify(func() error {
+		// Create/Modify/Delete pipeline resources as needed per new state
+		return m.step(e.pipeline, e.etcdVer, e.etcdRev)
+	}, backoff.NewInfiniteBackOff(), func(err error, d time.Duration) error {
```
[the remark this answers is not in the document]
Comment (PFedak) [reply src/server/pps/server/master.go:174]: I don't have a sense of what our real-world error distribution looks like here - clearly after my change we're a little less tolerant to errors since there are fewer overall retry attempts, but maybe that doesn't matter. Limiting the total time spent retrying sounds good. The main difference that would cause is by default ExponentialBackoff skips calling notify if it hits a timeout, which means master wouldn't attempt to fail the pipeline, but maybe working around that by moving the fail step outside of the backoff isn't so bad. Perhaps I'm worrying too much, though, since as you point out the poller will eventually fix things.

File: src/server/pps/server/pipeline_controller.go [hunk 5]
```diff
@@ -232,37 +231,29 @@ func (op *pipelineOp) run() error {
 // should be one of the first calls made on 'op', as most other methods (e.g.
 // getRC, though not failPipeline) assume that op.pipelineInfo is set.
 //
-// Like other functions in this file, it takes responsibility for failing op's
-// pipeline if it can't read the pipeline's info, and then returns an error to
-// the caller to indicate that the caller shouldn't continue.
+// Like other functions in this file, its errors signal that the whole step
+// should be retried, eventually failing op's pipeline
```
[the remark this answers is not in the document]
Comment (PFedak) [reply src/server/pps/server/pipeline_controller.go]: Done

File: src/server/pps/server/pipeline_controller.go [hunk 6]
```diff
@@ -232,37 +231,29 @@ func (op *pipelineOp) run() error {
...
 // exist--if set to 'rcExpected', getRC will restart the pipeline if no RC is
 // found after three retries. If set to 'noRCExpected', then getRC will return
 // after the first "not found" error. If set to noExpectation, then getRC will
-// retry the kubeclient.List() RPC, but will no restart the pipeline if no RC is
-// found
+// retry the kubeclient.List() RPC, but will not restart the pipeline if no RC
+// is found
 //
-// Like other functions in this file, it takes responsibility for restarting
+// Unike other functions in this file, it takes responsibility for restarting
```
[the remark this answers is not in the document]
Comment (PFedak) [reply src/server/pps/server/pipeline_controller.go]: Whoops

File: src/server/pps/server/master.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (PFedak) [reply src/server/pps/server/master.go]: I've left `retry` as a bool, I'm not entirely sure how the retry count logic would propagate if subsequent errors were different.

File: src/server/pps/server/master.go [hunk 7]
```diff
@@ -158,6 +175,42 @@ eventLoop:
...
+	}, backoff.NewExponentialBackOff(), func(err error, d time.Duration) error {
+		errCount++
+		if errors.As(err, &stepErr) {
+			if stepErr.retry && errCount < maxErrCount {
+				log.Errorf("PPS master: error updating resources for pipeline %q: %v; retrying in %v",
+					e.pipeline, err, d)
+				return nil
+			}
+		}
+		return errors.Wrapf(err, "could not update resource for pipeline %q: %v", e.pipeline)
```
Comment (msteffen) [inline src/server/pps/server/master.go:200]: Nit: format string needs to be updated (`%q: %v"` should just be `%q"`)

File: src/server/pps/server/pipeline_controller.go [hunk 8]
```diff
@@ -383,52 +378,33 @@ func (op *pipelineOp) rcIsFresh() bool {
...
-				"failed to create RC/service after %d attempts: %v", errCount, err))
-		default:
-			log.Errorf("PPS master: error creating resources for pipeline %q: %v; retrying in %v",
-				op.name, err, d)
-			return nil
+	if err := op.m.a.createWorkerSvcAndRc(op.opClient.Ctx(), op.ptr, op.pipelineInfo); err != nil {
+		if errors.As(err, &noValidOptionsErr{}) {
+			// these errors indicate invalid pipelineInfo, don't retry
+			return stepError{
+				error:        errors.Wrap(err, "could not generate RC options: %v"),
```
Comment (msteffen) [inline src/server/pps/server/pipeline_controller.go:401]: Nit: I think format string needs to be updated (no `%v`)

File: src/server/pps/server/pipeline_controller.go [hunk 9]
```diff
@@ -635,50 +578,20 @@ func (op *pipelineOp) scaleDownPipeline() (retErr error) {
...
+	// create up-to-date RC
+	if err := op.createPipelineResources(); err != nil {
+		return errors.Wrap(err, "error creating resources for restart")
+	}
+	if err := op.setPipelineState(pps.PipelineState_PIPELINE_RESTARTING, ""); err != nil {
+		return errors.Wrap(err, "error restarting pipeline")
 	}
-	return errors.Errorf("failing pipeline %q: %v", op.name, reason)
+
+	return errors.Errorf("restarting pipeline %q: %v", op.name, reason)
```
Comment (msteffen) [inline src/server/pps/server/pipeline_controller.go:596]: Nit: format string (no `%v`)

**Review by msteffen — APPROVED** [review]
LGTM, with a few nits regarding error text

File: src/server/pps/server/pipeline_controller.go (hunk 9 above)
Comment (PFedak) [reply src/server/pps/server/pipeline_controller.go]: I guess this was there before my change, but switched to %s. Sorry about the others, I could have sworn I did a pass to make sure none were left.
