### PR TITLE
Ignore output not finished errors when putting files via s3gateway

### LINKED ISSUE #4065: s3gateway: have an option to not serve etags
When objects are inserted via s3gateway (both multipart and non-multipart), we currently perform an `InspectFile` to determine the file's hash/etag. This does not work when files are being inserted on an open commit.

It's not clear what impact if any there would be in removing this etag - both in practice, and in conformance tests. If it's feasible to remove, it would remove a possible failure state for s3gateway.

### PR DESCRIPTION
**Pull request by ysimonson**
Closes #4065. This should be the best of both worlds: file hashes and versions will continue to be served when there are no open commits, and open commits will now be supported.

### CODE REVIEW

File: src/server/pfs/pfs.go [hunk 1]
```diff
@@ -56,6 +56,12 @@ type ErrParentCommitNotFound struct {
 	Commit *pfs.Commit
 }
 
+// ErrOutputCommitNotFinished represents an error where the commit has not
+// been finished
+type ErrOutputCommitNotFinished struct {
+	Commit *pfs.Commit
+}
+
```
Comment (jdoliner) [inline src/server/pfs/pfs.go]: Nice, I like adding this to the enumerated pfs erors.
