### PR TITLE
Fix #260

### LINKED ISSUE #260: Make sure that every shard starts with some input data
When `max(blocks_per_file) < shards`, or `num_files < shards` in the case of a reduce job, some shards are started without any input data at all.  This results in resources being wasted, and some jobs might even fail if they do not shut down gracefully with empty data.

### PR DESCRIPTION
**Pull request by derekchiang**
This PR does a few things:

* Allow pipelines to have no inputs
* For pipelines with inputs, we dynamically adjust the number of parallel jobs to ensure that every job starts with some input data.  For pipelines that don't have inputs, we use the degree of parallelism specified by the user.
* Add a `run-pipeline` command that can be used to manually trigger pipelines
* Fix a bug that allowed `ListCommit` to return cancelled commits when it shouldn't
* Add a `recurse` flag to `ListFile` that makes it correctly compute the size of sub-directories at the cost of reduced performance.

### CODE REVIEW

File: src/server/pfs/cmds/cmds.go [hunk 1]
```diff
@@ -328,7 +328,7 @@ Files can be read from finished commits with get-file.`,
 			if len(args) == 3 {
 				path = args[2]
 			}
-			fileInfos, err := pfsclient.ListFile(apiClient, args[0], args[1], path, "", shard())
+			fileInfos, err := pfsclient.ListFile(apiClient, args[0], args[1], path, "", shard(), true)
```
Comment (jdoliner) [inline src/server/pfs/cmds/cmds.go]: So we're defaulting to a recursive list file? Does that behavior match what we had before?

Comment (derekchiang) [inline src/server/pfs/cmds/cmds.go]: To be clear, setting the `recurse` option to true means that we will correctly compute the sizes of children directories at the cost of performance.  I think this is a reasonable tradeoff for `pachctl` since `pachctl` is meant to be used manually (as opposed to programmatically), and the human user probably expects to see the correct sizes of directories.

This does not match what we had before, since before if you did `list-file`, you'd see child directories' sizes being zero.

Comment (jdoliner) [inline src/server/pfs/cmds/cmds.go]: I see, that behavior for pachctl seems reasonable. The name `recurse` is a little weird imo though. Since I'd expect it to mean that we actually return records for the files in subdirectories not just include them in size counts. Do you think there's another name that describes this better? I can't think of one of the top of my head.

File: src/server/pfs/fuse/filesystem.go [hunk 2]
```diff
@@ -472,6 +472,9 @@ func (d *directory) readFiles(ctx context.Context) ([]fuse.Dirent, error) {
 		d.File.Path,
 		d.fs.getFromCommitID(d.File.Commit.Repo.Name),
 		d.Shard,
+		// setting recurse to false for performance reasons
+		// it does however means that we won't know the correct sizes of directories
+		false,
```
Comment (jdoliner) [inline src/server/pfs/fuse/filesystem.go]: It's fine to not know the correct sizes of directories, `ls` doesn't report the size of files stored in directories for normal filesystems either. And generally speaking the size of directory shown by `ls` isn't normally taken to be the size of the objects contained in it.

File: src/server/pps/cmds/cmds.go [hunk 3]
```diff
@@ -312,6 +319,69 @@ All jobs created by a pipeline will create commits in the pipeline's repo.
...
+			apiClient, err := getAPIClient(address)
+			if err != nil {
+				return err
+			}
+			pipelineName := args[0]
+			pipelineInfo, err := apiClient.InspectPipeline(context.Background(), &ppsclient.InspectPipelineRequest{
+				Pipeline: &ppsclient.Pipeline{
+					Name: pipelineName,
+				},
+			})
```
Comment (jdoliner) [inline src/server/pps/cmds/cmds.go]: How hard would it be make this logic be serverside? I generally feel a little uneasy with putting real logic in frontend things like pachctl because it creates this walled garden of stuff you can do with pachctl but can't do using other interfaces such as the go api.

File: src/server/pps/server/api_server.go [hunk 4]
```diff
@@ -145,26 +150,87 @@ func (a *apiServer) CreateJob(ctx context.Context, request *ppsclient.CreateJobR
...
+					break CheckInputs
+				}
+			}
+		}
+	}
+
+	if len(viableFilterShards) == 0 && len(request.Inputs) > 0 {
+		return nil, ErrEmptyInput
+	}
+
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: I got a little bit confused trying to understand this logic, how would you feel about calling `viableFilterShards` `nonEmptyFilterShards` instead? I think that would have helped me get it sooner.

**Comment by jdoliner** [comment]
With the exception of those few comments everything here LGTM.

I'd also like to see a test for `run-pipeline` which is another good reason for putting the logic server side rather than in pachctl.

File: src/server/pps/cmds/cmds.go (hunk 3 above)
Comment (derekchiang) [inline src/server/pps/cmds/cmds.go]: Putting this logic server side would require us to create `RunPipelineRequest` and a `RunPipeline` API, right?  I don't have a problem with that necessarily; just wondering if that's the only way to do it.

Comment (jdoliner) [inline src/server/pps/cmds/cmds.go]: I was thinking that we could augment the semantics of `CreateJob` a little bit to get us there. Basically make it so that you can call `CreateJob` with just `CreateJobRequest.Pipeline` set and it will go to the db to find the transform. We could probably then simplify the way we call `CreateJob` from `runPipeline` as well. Does that make sense?

Comment (derekchiang) [inline src/server/pps/cmds/cmds.go]: I already added `RunPipeline` and `RunPipelineRequest` and it doesn't look too bad.  It will probably scale better as well since we might be adding more options to `RunPipelineRequest` in the future.

Comment (jdoliner) [inline src/server/pps/cmds/cmds.go]: I have a pretty strong preference for keeping it a single request. It seems like any option we could possible want to add to `RunPipeline` we're also going to want on `CreateJob` so we're just setting ourselves up to either implement everything twice or have their functionality diverge.

**Comment by derekchiang** [comment]
@jdoliner take another look?

File: src/server/pachyderm_test.go [hunk 5]
```diff
@@ -363,6 +363,107 @@ func TestPipeline(t *testing.T) {
...
+	require.NoError(t, pfsclient.FinishCommit(pachClient, dataRepo, commit1.ID))
+	listCommitRequest := &pfsclient.ListCommitRequest{
+		Repo:       []*pfsclient.Repo{outRepo},
+		CommitType: pfsclient.CommitType_COMMIT_TYPE_READ,
+		Block:      true,
+	}
+	listCommitResponse, err := pachClient.ListCommit(
+		context.Background(),
+		listCommitRequest,
+	)
```
Comment (jdoliner) [inline src/server/pachyderm_test.go]: Would you mind doing an `InspectJob` here like in the other tests? Also add a timeout to the context so that the test can error after like 30 seconds rather than blocking indefinitely and causing a timeout.

File: src/server/pps/persist/persist.proto [hunk 6]
```diff
@@ -42,7 +43,7 @@ message JobState {
 message PipelineInfo {
   string pipeline_name = 1;
   pachyderm.pps.Transform transform = 2;
-  uint64 shards = 3;  // this is the degree of parallelism
+  uint64 parallelism = 3;  // this is the degree of parallelism
```
Comment (jdoliner) [inline src/server/pps/persist/persist.proto]: Could you remove this comment? Now that it's called parallelism it seems like the comment isn't telling us much.

Comment (derekchiang) [inline src/server/pps/persist/persist.proto]: nah we should change it to `this is the number of shards` for clarify

Comment (jdoliner) [inline src/server/pps/persist/persist.proto]: lol @derekchiang big lol

**Comment by jdoliner** [comment]
This LGTM after those 2 things are fixed.

File: src/server/pachyderm_test.go (hunk 5 above)
Comment (derekchiang) [inline src/server/pachyderm_test.go]: Wait but this is a pipeline test. What job do I inspect?

Comment (jdoliner) [inline src/server/pachyderm_test.go]: Oh good point. I guess you would have to do a `ListJob` first, that's a bit of a pain though so maybe just add the timeout to the call to `ListCommit` and call it a day.
