### PR TITLE
Fix token propagation for StopJob & refactor pps

### LINKED ISSUE #4081: Crash when setting `EXPOSE_OBJECT_API=true` with pachd 1.8.6
**What happened?**:
I changed the value of the EXPOSE_OBJECT_API from 'false' to 'true' and pachd crashed on startup with this output:
```
2019-09-10T17:09:10Z WARNING TLS disabled: could not stat public cert at /pachd-tls-cert/tls.crt: stat /pachd-tls-cert/tls.crt: no such file or directory
2019-09-10T17:09:10Z WARNING TLS disabled: could not stat private key at /pachd-tls-cert/tls.key: stat /pachd-tls-cert/tls.key: no such file or directory
2019-09-10T17:09:10Z INFO Using cloudfront security credentials - keypair ID (APKAJKDBUNGUQRHTVH6Q) - to sign cloudfront URLs
2019-09-10T17:09:10Z INFO validating kubernetes access returned no errors
2019-09-10T17:09:10Z INFO Using cloudfront security credentials - keypair ID (APKAJKDBUNGUQRHTVH6Q) - to sign cloudfront URLs
2019-09-10T17:09:10Z INFO validating kubernetes access returned no errors
panic: duplicate registration of group object

goroutine 131 [running]:
github.com/pachyderm/pachyderm/src/server/vendor/github.com/golang/groupcache.newGroup(0x219acf8, 0x6, 0x0, 0x243b440, 0xc0002f0550, 0x0, 0x0, 0x0)
        src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/golang/groupcache/groupcache.go:96 +0x338
github.com/pachyderm/pachyderm/src/server/vendor/github.com/golang/groupcache.NewGroup(0x219acf8, 0x6, 0x0, 0x243b440, 0xc0002f0550, 0x0)
        src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/golang/groupcache/groupcache.go:84 +0x5b
github.com/pachyderm/pachyderm/src/server/pfs/server.newObjBlockAPIServer(0xc00005a04b, 0x4, 0x0, 0xc0001ca060, 0x19, 0x2475200, 0xc00077c8c0, 0x0, 0x0, 0x2260e98, ...)
        src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:97 +0x26e
github.com/pachyderm/pachyderm/src/server/pfs/server.newAmazonBlockAPIServer(0xc00005a04b, 0x4, 0x0, 0xc0001ca060, 0x19, 0x3a355a0, 0x2165f60, 0xc0003670e0)
        src/github.com/pachyderm/pachyderm/src/server/pfs/server/obj_block_api_server.go:177 +0xb1
github.com/pachyderm/pachyderm/src/server/pfs/server.NewBlockAPIServer(0xc00005a04a, 0x5, 0x0, 0xc0000560b0, 0x6, 0xc0001ca060, 0x19, 0xc000058075, 0x15, 0xc000058049, ...)
        src/github.com/pachyderm/pachyderm/src/server/pfs/server/server.go:52 +0x284
main.doFullMode.func7.1(0xc0004ed080, 0x6, 0x6)
        src/github.com/pachyderm/pachyderm/src/server/cmd/pachd/main.go:355 +0xd65
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/grpcutil.Serve(0xc0005604b0, 0x1, 0x1, 0x7f36ba658600, 0xc000001c80)
        src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pkg/grpcutil/server.go:107 +0x2ad
main.doFullMode.func7(0x8, 0x2265888)
        src/github.com/pachyderm/pachyderm/src/server/cmd/pachd/main.go:310 +0x24c
github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000560450, 0xc00043e150)
        src/github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup.(*Group).Go
        src/github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**What you expected to happen?**:
I expected the object API to be enabled so I could use `pachctl get-object`

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI and pachd server version (use `pachctl version`): 1.8.6 for both

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
AWS, object store on S3

- OS (e.g. from /etc/os-release):
ubuntu 18.04

- Others:

### PR DESCRIPTION
**Pull request by msteffen**
Fixes #4081

### CODE REVIEW

File: src/server/cmd/pachd/main.go [hunk 1]
```diff
@@ -406,7 +406,8 @@ func doFullMode(config interface{}) (retErr error) {
 						blockAPIServer, err := pfs_server.NewBlockAPIServer(
 							env.StorageRoot,
 							0 /* = blockCacheBytes (disable cache) */, env.StorageBackend,
-							etcdAddress)
+							etcdAddress,
+							true /* duplicate */)
```
Comment (jdoliner) [inline src/server/cmd/pachd/main.go]: Looks like this will solve #4081.

Comment (jdoliner) [reply src/server/cmd/pachd/main.go]: Just updated the description of this PR so it will auto close that issue when it's merge. Obviously remove that if it's not true, but it seems like as part of this PR you've tested the expose object api flag with this.

Comment (msteffen) [reply src/server/cmd/pachd/main.go]: Sweet! I didn't know about the issue, but this should fix it. I am curious why an external user would be interested in it, but I posted that in the issue
