### PR TITLE
Remove orphaned jobs

### LINKED ISSUE #1289: Cannot clean up orphaned job
Following the [opencv tutorial](https://github.com/pachyderm/pachyderm/tree/master/doc/examples/opencv), I first tried to `create-pipeline` with the file provided in the repo, to see what would happen, even though instructions say to change the image.  I see the pipeline was stuck in the pulling state, and `kubectl` shows the pod in an `ImagePullBackOff` with an error along the lines of not being able to find an image in Docker Hub `library/opencv`.  Makes sense.

I found the `opencv` image made by the person who last commited to the README, and decided to use their Docker image rather than building and distributing my own.  That worked fine, but it left the old job that was bound to fail sitting around forever:

```
$ pachctl list-job
ID                                 OUTPUT COMMIT                              STARTED             DURATION            STATE
db836ed00a62e660240dd83ce211db2b   edges/2b54c9fae81847dcaed353237169d65b/0   11 minutes ago      2 minutes           success
245d076e2e8ea40dcece42c9584f1a1d   edges/9c2f2e8aa98a4208a361b93a4e05bd3e/0   14 minutes ago      -                   pulling
```

I even deleted the job from Kubernetes directly, but the job still shows up in Pachyderm.  I can't delete the job in Pachyderm, because:

```
$ pachctl delete-job 245d076e2e8ea40dcece42c9584f1a1d
error from DeleteJob: cannot delete job (245d076e2e8ea40dcece42c9584f1a1d) that belongs to a pipeline (edges)
```

I had to `delete-all`.

Would this have eventually cleaned itself up?  Even if I hadn't manually deleted the job in Kubernetes, would it still eventually clean itself up?

### PR DESCRIPTION
**Pull request by derekchiang**
This PR removes support for "orphaned jobs", i.e. jobs without pipelines.  The reasons why we decided to remove them are:

* The feature is rarely, if ever, used.
* The feature is not well tested, if at all.
* The implementation of the feature complicates the codebase.

Fix #1289

### CODE REVIEW

File: src/server/pps/server/api_server.go [hunk 1]
```diff
@@ -755,17 +738,19 @@ func translatePipelineInputs(inputs []*pps.PipelineInput) *pps.Input {
...
+		atomInput := &pps.AtomInput{
+			Name:       input.Name,
+			Branch:     input.Branch,
+			Glob:       input.Glob,
+			Lazy:       input.Lazy,
+			FromCommit: fromCommitID,
+		}
+		if input.Repo != nil {
+			atomInput.Repo = input.Repo.Name
+		}
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: Is it possible for `Input.Repo` to be `nil` in this PR? That doesn't seem like it should be a valid input.

**Comment by jdoliner** [comment]
LGTM
