### PR TITLE
Fix lazy propagation

### LINKED ISSUE #1333: Not propagating the `lazy` field
...  for pipelines that have inputs that are not raw inputs

### PR DESCRIPTION
**Pull request by sjezewski**
Fixes #1333

### CODE REVIEW

File: src/server/pps/server/api_server.go [hunk 1]
```diff
@@ -2072,6 +2072,7 @@ func (a *apiServer) trueInputs(
 					Commit:   commitInfo.Commit,
 					Method:   pipelineInput.Method,
 					RunEmpty: pipelineInput.RunEmpty,
+					Lazy:     pipelineInput.Lazy,
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: >.< Pretty sure I wrote this initially.

Comment (sjezewski) [inline src/server/pps/server/api_server.go]: :-P computers are hard
