### PR TITLE
Fix fuse big reads

### LINKED ISSUE #833: FUSE can't read files larger than a block
Walk through TF example to validate it works well w refactor

### PR DESCRIPTION
**Pull request by sjezewski**
Fixes #833 (where most of the bug discussion is).

### CODE REVIEW

**Comment by sjezewski** [comment]
Also updated the `pipeline.json` spec to use new `parallelism_spec` field so that the example will run w whats on master

File: src/server/pfs/db/driver.go [hunk 1]
```diff
@@ -1322,7 +1322,12 @@ func (r *fileReader) Read(data []byte) (int, error) {
 			break
 		}
 		client := client.APIClient{BlockAPIClient: r.blockClient}
-		r.reader, err = client.GetBlock(blockRef.Hash, uint64(r.offset), uint64(r.size))
+		sizeLeft := r.size
+		// e.g. sometimes a reader is constructed of size 0
+		if r.size > r.sizeRead {
```
Comment (jdoliner) [inline src/server/pfs/db/driver.go]: This should always be true unless `r.size` is `0` right?
Assuming that's true I think it'd be clearer to just do: `if sizeLeft != 0`

Comment (sjezewski) [inline src/server/pfs/db/driver.go]: Yup! I'll make that change
