### PR TITLE
Fix a bug where when PPS reshards, some pipelines can end up with no workers

### LINKED ISSUE #1787: PPS re-sharding leaves some pipelines running without workers
Occasionally, a node can fail over for whatever reason, which causes PPS to re-shard.  When this happens, some pipelines can somehow end up with no workers.  This is likely due to a race between one process deleting the underlying replication controller and another process re-creating it.

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #1787

### CODE REVIEW

File: src/server/pps/server/api_server.go [hunk 1]
```diff
@@ -1337,16 +1345,6 @@ func (a *apiServer) workerServiceIP(ctx context.Context, deploymentName string)
...
-	go func() {
-		// Clean up workers if the pipeline gets cancelled
-		<-ctx.Done()
-		rcName := PipelineRcName(pipelineInfo.Pipeline.Name, pipelineInfo.Version)
-		if err := a.deleteWorkers(rcName); err != nil {
-			protolion.Errorf("error deleting workers for pipeline: %v", pipelineName)
-		}
-		protolion.Infof("deleted workers for pipeline: %v", pipelineName)
-	}()
-
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: It seems like there's probably a matching call to create the workers that might error now because the workers already exist. Is that true and if so do we trap that error in some way?

Comment (derekchiang) [inline src/server/pps/server/api_server.go]: We do trap the error if the workers already exist.
