### PR TITLE
Fix bad output repo stats

### LINKED ISSUE #3330: `pachctl list-repo` results in output repo showing SIZE 0B when output repo has files in it
**What happened?**:
`pachctl list-repo` results in output repo showing SIZE 0B
However, `list-file` shows SIZE > 0B 

screenshot:

screen shot 2019-01-04 at 2 05 28 pm

**What you expected to happen?**:
`pachctl list-repo` result in output repo showing SIZE > 0B 
and you can see the files in the output repo

**How to reproduce it (as minimally and precisely as possible)?**:
- create an input repo
- create an output repo
- pachyderm pipeline saves files to a subdirectory in the output repo
- `pachctl list-repo` 

Output repo should show SIZE 0B

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 0.30.0
- Pachyderm CLI version (use `pachctl version`): 1.8.0
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):minikube
- OS (e.g. from /etc/os-release): Mac

### PR DESCRIPTION
**Pull request by ysimonson**
Repo sizes are now set to be the size of the master branch's HEAD commit.

Open questions:
* Can the master branch be deleted? If so, how should that case be handled?
* Are there any other places where the HEAD commit might be changed?

Fixes #3330

### CODE REVIEW

File: src/server/pfs/server/driver.go [hunk 1]
```diff
@@ -531,7 +532,8 @@ func (d *driver) makeCommit(pachClient *client.APIClient, ID string, parent *pfs
 		}
 
 		// BuildCommit case: Now that 'parent' is resolved, read the parent commit's
-		// tree (inside txn) and update the repo size
+		// tree (inside txn)
+		isOpen := false
```
Comment (jdoliner) [inline src/server/pfs/server/driver.go]: `isOpen` is a slightly confusing name to me, after reading a bit I think it indicates that the commit is being started by this call (which I had actually forgotten this call could do) but at first I thought it indicated that the commit was open before the call started. Maybe we could call it `isStartCommit` or something, I think that'd remove any confusion.

File: src/server/pfs/server/driver.go [hunk 2]
```diff
@@ -531,7 +532,8 @@ func (d *driver) makeCommit(pachClient *client.APIClient, ID string, parent *pfs
 		}
 
 		// BuildCommit case: Now that 'parent' is resolved, read the parent commit's
-		// tree (inside txn) and update the repo size
+		// tree (inside txn)
```
Comment (jdoliner) [inline src/server/pfs/server/driver.go]: I think this comment should be below the line below, or maybe just inside the if block since I think that's what it applies to and it would prevent it getting separated from the code it's commenting on.

**Comment by jdoliner** [comment]
2 small changes requested.

**Comment by ysimonson** [comment]
@jdoliner this is ready for another pass. TravisCI says it's still running tests for the PR, but they passed hours ago - you can see if you click through.
