### PR TITLE
Make PPS master tolerant of failures in creating workers

### LINKED ISSUE #2001: PPS gets stuck if it fails to create workers for a pipeline
Reported by @JoeyZwicker.  Steps to reproduce:

* Create a pipeline whose parallelism spec is such that both `coefficient` and `constant` are 0.
* Observe that no workers are created.
* Create some (valid) pipelines.
* Observe that no workers are created for those pipelines.

### PR DESCRIPTION
**Pull request by derekchiang**
Fix #2001.  Additionally validate parallelism spec.

### CODE REVIEW

File: src/server/pps/server/api_server.go [hunk 1]
```diff
@@ -600,6 +600,9 @@ func (a *apiServer) validatePipeline(ctx context.Context, pipelineInfo *pps.Pipe
 	if pipelineInfo.OutputBranch == "" {
 		return fmt.Errorf("pipeline needs to specify an output branch")
 	}
+	if pipelineInfo.ParallelismSpec != nil && pipelineInfo.ParallelismSpec.Constant == 0 && pipelineInfo.ParallelismSpec.Coefficient == 0 {
+		return fmt.Errorf("cannot specify 0 for both constant and coefficient in parallelism spec")
+	}
```
Comment (jdoliner) [inline src/server/pps/server/api_server.go]: Shouldn't this really check if `Strategy == "CONSTANT" && Constant == 0`? Joey hit this error because he was unwittingly setting `Strategy == "COEFFICIENT"` but only setting `Constant` to a nonzero number.

**Comment by JoeyZwicker** [comment]
Aren't we getting rid of strategy completely? Wouldn't it make sense to do
those PR's at the same time instead of writing logic for checking
`strategy`?

**Comment by derekchiang** [comment]
Yeah like @JoeyZwicker said I think the fix for #2000 will make the parallelism spec validation code in this PR obsolete.  I will reduce the scope of this PR to only making PPS master tolerant of kube-related failures.

File: src/server/pps/server/master.go [hunk 2]
```diff
@@ -106,29 +113,55 @@ func (a *apiServer) master() {
...
+		if err := pipelines.Get(pipelineName, pipelineInfo); err != nil {
+			return err
+		}
+		pipelineInfo.State = pps.PipelineState_PIPELINE_FAILURE
+		pipelines.Put(pipelineName, pipelineInfo)
+		return nil
+	})
+	return err
+}
+
```
Comment (jdoliner) [inline src/server/pps/server/master.go]: Will pipelines that are in failure state automatically recover and get out of failure state? Or is there some action the user needs to take?

Comment (derekchiang) [inline src/server/pps/server/master.go]: We don't automatically recover (since it's unclear how to recover if k8s won't let you create workers), and there's no meaningful action that the user can take other than maybe rebooting the cluster and hope that something happens.  This PR mostly tries to solve the problem that currently if we fail to create workers for a pipeline, all subsequent pipeline creations are ignored.
